### ISSUE TITLE
Cannot produce a deterministic build

### ISSUE THREAD

**Issue by mmikitka** [openssl/openssl#10061]
If you invoke `./config` multiple times in succession the checksums of the auto-generated files will not be equal. In particular, the following differences were observed:

1. The "built on" timestamp, declared in util/mkbuildinf.pl extracts the current date/time by default. However, the code suggests that this can be overriden by the SOURCE_DATE_EPOCH environment variable

2. The array values in configdata.pm are not deterministic

3. The array values in Makefile are not deterministic (e.g., DEPS)

**Comment by mattcaswell** [comment]
PR #10062 was closed without merge so a new fix is required for this.

**Comment by t8m** [comment]
This was fixed by #25699

**Comment by tbarrella** [comment]
Hello, while #25699 fixed the timestamp issue, I think

>The array values in Makefile are not deterministic (e.g., DEPS)

is still an issue. Would it be ok to reopen this issue @t8m?

**Comment by t8m** [comment]
@tbarrella Please open a new issue clearly describing the remaining issue with the deterministic build. Or, even better, submit a PR with a fix.
