### ISSUE TITLE
openssl 3.0.0-alpha13 test_fipsinstall: openssl.exe crashes

### ISSUE THREAD

**Issue by gv74** [openssl/openssl#13338]
$ perl Configure --prefix="C:\PD" --libdir="bin" --openssldir="C:\PD\ssl" enable-camellia enable-seed VC-WIN64A
$ nmake all
$ nmake test TESTS=test_fipsinstall V=1
A window with the message "OpenSSL has stopped working" appear several times.

**Comment by gv74** [comment]
![crash](https://user-images.githubusercontent.com/74062284/98405554-5af8b800-2064-11eb-986d-bba2aa5b41e5.png)

**Comment by gv74** [comment]
[test_fipsinstall.log](https://github.com/openssl/openssl/files/5503051/test_fipsinstall.log)

**Comment by mattcaswell** [comment]
Strange. The test log shows that the tests actually pass!

This line (repeated several times) looks odd:

````
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
````

**Comment by gv74** [comment]
I have to click "Close the program"  14 times during the test. And to advance from test n to n+1 you need to click 2 times (2 pop-up windows). The "cmd.exe" message is printed on screen after the second click.

**Comment by mattcaswell** [comment]
Is it just this test that shows this behaviour, or do other tests do the same thing?

**Comment by gv74** [comment]
Just this one.

**Comment by mattcaswell** [comment]
Doing some googling suggests that this *might* have something to do with the perl "system" function producing spurious errors. What version of perl are your running?

**Comment by gv74** [comment]
I fail to see how exactly perl can cause openssl to crash.
But anyway...

C:\>perl --version
This is perl 5, version 26, subversion 1 (v5.26.1) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

**Comment by gv74** [comment]
All crashes are in o_str.c on line 67. str argument for OPENSSL_strnlen() is invalid. str is initialized on b_print.c: on line 301:
strvalue = va_arg(args, char *);

full stack:

libcrypto-3.dll!OPENSSL_strnlen(const char * str, unsigned __int64 maxlen) Line 67
libcrypto-3.dll!fmtstr(char * * sbuffer, char * * buffer, unsigned __int64 * currlen, unsigned __int64 * maxlen, const char * value, int flags, int min, int max) Line 378
libcrypto-3.dll!_dopr(char * * sbuffer, char * * buffer, unsigned __int64 * maxlen, unsigned __int64 * retlen, int * truncated, const char * format, char * args) Line 311
[Inline Frame] libcrypto-3.dll!BIO_vsnprintf(char * buf, unsigned __int64 n, const char *) Line 921
libcrypto-3.dll!BIO_snprintf(char * buf, unsigned __int64 n, const char * format, ...) Line 910
libcrypto-3.dll!ERR_print_errors_cb(int(*)(const char *, unsigned __int64, void *) cb, void * u) Line 63
openssl.exe!fipsinstall_main(int argc, char * * argv) Line 514
openssl.exe!do_cmd(lhash_st_FUNCTION * prog, int argc, char * * argv) Line 411
openssl.exe!main(int argc, char * * argv) Line 297

My openssl is not compiled in debug mode so I cannot see values for variables. I may try to build a debug version.

**Comment by mattcaswell** [comment]
> Doing some googling suggests that this might have something to do with the perl "system" function producing spurious errors.

Looks like the "Can't spawn" error and "click 2 times" per test are a bit of a red herring. I've just replicated that behaviour on my system (without the crash), and it does seem to be something strange related to perl. On my system if perl runs an application that returns a "failure" result code (as is expected behaviour in this test) it for some unknown reason seems to run the application twice and after the second time prints the "Can't spawn" error message. In spite of that it seems to otherwise work (on my system) and the tests still pass.

@levitte - can you shed any light on this strange behaviour?

So it looks like the crash is an independent problem from the "Can't spawn" one.

> My openssl is not compiled in debug mode so I cannot see values for variables. I may try to build a debug version.

That would be very helpful.

**Comment by gv74** [comment]
The crash start in crypto/err/err_prn.c:29, fnc: ERR_print_errors_cb():
	while ((l = ERR_get_error_all(&file, &line, &func, &data, &flags)) != 0) {
"file" and "func" pointer come out of ERR_get_error_all (aka get_error_values()) invalid.

Because of this "args" in BIO_snprintf() function become corrupted and we have a crash.

So I replaced (just for testing) the following call:
       BIO_snprintf(buf, sizeof(buf), "%s:error::%s:%s:%s:%s:%d:%s\n",
                     hex == NULL ? "<null>" : hex, lib, fnc, reason, file,
                     line, data);
with this:
       BIO_snprintf(buf, sizeof(buf), "%s:error::%s:%s:%s:%s:%d:%s\n",
                     hex == NULL ? "<null>" : hex, lib, /*func*/ "fnc", reason, /*file*/ "file",
                     line, data);
This seems to fix the initial crash but now it crashes in crypto/initthread.c:313, fnc: init_thread_stop().
The line is:
curr->handfn(curr->arg);
It seems args is NULL so, again, we have a crash.
I changed the code like this:
        if (curr->arg)
            curr->handfn(curr->arg);
and now works (this check is probably a good ideea).

Running the selftest again, instead of crashing, the following text appears on screen:
INSTALL FAILED
DC030000:error::Provider routines:fnc:module integrity failure:file:277:
DC030000:error::Provider routines:fnc:fips module entering error state:file:350:
DC030000:error::Provider routines:fnc:self test post failure:file:626:
DC030000:error::common libcrypto routines:fnc:init fail:file:537:
DC030000:error::configuration file routines:fnc:module initialization error:file:243:module=providers, value=provider_section, retcode=-1      

Howver, this does not fix the real problem. The issue is: why ERR_STATE in get_error_values() have invalid values for file and func (lines 464 and 905 in err.c). Because line number is to be OK, see Linux output:

INSTALL FAILED
C0F2CE9BEE7F0000:error::Provider routines:SELF_TEST_post:self test kat failure:providers/fips/self_test.c:316:
C0F2CE9BEE7F0000:error::Provider routines:ossl_set_error_state:fips module entering error state:providers/fips/self_test.c:350:
C0F2CE9BEE7F0000:error::Provider routines:OSSL_provider_init:self test post failure:providers/fips/fipsprov.c:626:
C0F2CE9BEE7F0000:error::common libcrypto routines:provider_activate:init fail:crypto/provider_core.c:537:
C0F2CE9BEE7F0000:error::configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:243:module=providers, value=provider_section, retcode=-1

**Comment by gv74** [comment]
I'm very sorry, copy/paste the wrong output. The linux output is:
INSTALL FAILED
C0020C16987F0000:error::Provider routines:SELF_TEST_post:module integrity failure:providers/fips/self_test.c:277:
C0020C16987F0000:error::Provider routines:ossl_set_error_state:fips module entering error state:providers/fips/self_test.c:350:
C0020C16987F0000:error::Provider routines:OSSL_provider_init:self test post failure:providers/fips/fipsprov.c:626:
C0020C16987F0000:error::common libcrypto routines:provider_activate:init fail:crypto/provider_core.c:537:
C0020C16987F0000:error::configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:243:module=providers, value=provider_section, retcode=-1

**Comment by gv74** [comment]
OK. I think I have pinpoint the problem in openssl.

1. In self-test.c:277, (SELF_TEST_post()) the error is set::
`	ERR_raise(ERR_LIB_PROV, PROV_R_MODULE_INTEGRITY_FAILURE);`
The file and func are local variables in fips module.

2. ERR_raise() macro will call err_set_debug(), err_local.h:52.
The file name and the function pointers are are assigned to ERR_STATE *es:
```
    es->err_file[i] = file;
    es->err_func[i] = fn;
```

3. openssl execution will reach provider_core.c:540 that call:
	`DSO_free(prov->module);`
This will **destroy** all memory used by fips module and now ERR_STATE *es will have two invalid pointers (`es->err_file` and `es->err_func`).
That I do not understand why the DSO_free() is executed since is guarded by #ifndef FIPS_MODULE.

4. openssl execution reach fipsinstall.c:510 (fipsinstall_main()) and will execute ERR_print_errors(bio_err); And, of course, since `es` refers an invalid memory, openssl will crash.

**Comment by gv74** [comment]
Searching in makefile for provider_core.c that does not have FIPS_MODULE define:
```
$ grep provider_core\.c makefile | grep -v FIPS_MODULE | grep CC
        $(CC)  $(LIB_CFLAGS) -I "." -I "include" -I "providers\common\include" -I "providers\implementations\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c $(COUTFLAG)$@ "crypto\provider_core.c"
        $(CC)  $(LIB_CFLAGS) -I "." -I "include" -I "providers\common\include" -I "providers\implementations\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM /Zs /showIncludes "crypto\provider_core.c" 2>&1 > crypto\libcrypto-shlib-provider_core.d
        $(CC)  $(LIB_CFLAGS) -I "." -I "include" -I "providers\common\include" -I "providers\implementations\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c $(COUTFLAG)$@ "crypto\provider_core.c"
        $(CC)  $(LIB_CFLAGS) -I "." -I "include" -I "providers\common\include" -I "providers\implementations\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM /Zs /showIncludes "crypto\provider_core.c" 2>&1 > crypto\libcrypto-lib-provider_core.d
```

Searching in makefile for provider_core.c that does have FIPS_MODULE define:
```
$ grep provider_core\.c makefile | grep FIPS_MODULE | grep CC
        $(CC)  $(LIB_CFLAGS) -I "." -I "crypto" -I "include" -I "providers\implementations\include" -I "providers\common\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DFIPS_MODULE -DGHASH_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DX25519_ASM -c $(COUTFLAG)$@ "crypto\provider_core.c"
        $(CC)  $(LIB_CFLAGS) -I "." -I "crypto" -I "include" -I "providers\implementations\include" -I "providers\common\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DFIPS_MODULE -DGHASH_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DX25519_ASM /Zs /showIncludes "crypto\provider_core.c" 2>&1 > crypto\libfips-lib-provider_core.d
```

And I'm not sure what's this:
`FIPSMODULENAME=Program fragment delivered error ``Can't locate object method "basename" via package "platform" at Configurations\windows-makefile.tmpl line 60.''
`

**Comment by levitte** [comment]
> And I'm not sure what's this:
> `FIPSMODULENAME=Program fragment delivered error ``Can't locate object method "basename" via package "platform" at Configurations\windows-makefile.tmpl line 60.''
> `

Does this help?

``` diff
diff --git a/Configurations/windows-makefile.tmpl b/Configurations/windows-makefile.tmpl
index ce042d6ee8..ad7ff1d933 100644
--- a/Configurations/windows-makefile.tmpl
+++ b/Configurations/windows-makefile.tmpl
@@ -57,7 +57,7 @@ FIPSMODULENAME={- # We do some extra checking here, as there should be only one
                              && $unified_info{attributes}->{modules}->{$_}->{fips} }
                       @{$unified_info{modules}};
                   die "More that one FIPS module" if scalar @fipsmodules > 1;
-                  join(" ", map { basename platform->dso($_) } @fipsmodules) -}
+                  join(" ", map { basename(platform->dso($_)) } @fipsmodules) -}
 PROGRAMS={- our @PROGRAMS = map { platform->bin($_) } @{$unified_info{programs}}; join(" ", @PROGRAMS) -}
 PROGRAMPDBS={- join(" ", map { $_.".pdb" } @{$unified_info{programs}}) -}
 SCRIPTS={- our @SCRIPTS = @{$unified_info{scripts}}; join(" ", @SCRIPTS) -}
```

**Comment by levitte** [comment]
The printing errors issue after a module (DSO) is unloaded isn't something new, we had that problem with ENGINEs.  We should really copy all the strings that are given...  and those should be char arrays in ERR_STATE, just to avoid memory allocation problems.

**Comment by gv74** [comment]
> Does this help?

Yes. 

`FIPSMODULENAME=fips.dll`

**Comment by gv74** [comment]
> We should really copy all the strings that are given... and those should be char arrays in ERR_STATE, just to avoid memory allocation problems.
I agree.

**Comment by slontis** [comment]
> That I do not understand why the DSO_free() is executed since is guarded by #ifndef FIPS_MODULE.

There are 2 copies of provider_core.c.. The one you are looking at is inside libcrypto which gets used by the fipsinstall app (hence it doesnt have the #ifdef). The seoncd copy sits inside the fips module and will have the define set.

**Comment by gv74** [comment]
openssl 3.0.0-alpha10: nothing changed in this release related to the problem reported above..

**Comment by mattcaswell** [comment]
I question the OTC evaluated "3.0.0" milestone against this. I would have thought this needs to be a beta1 thing.

**Comment by gv74** [comment]
Now `15-test_ecparam.t` crashes too:

```
# Parameters are valid
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe pkeyparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\noncanon\wap-wsg-idm-ecid-wtls10-explicit.pem => 0
    ok 23
# Parameters are valid
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe pkeyparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\noncanon\wap-wsg-idm-ecid-wtls11-explicit.pem => 0
    ok 24
ok 6 - Check loading non-canonically encoded parameters by pkeyparam with -check
# Subtest: Check loading invalid parameters by ecparam with -check
    1..4
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem => 255
    ok 1
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem => 255
    ok 2
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem => 255
    ok 3
checking elliptic curve parameters: failed
74090000:error:0800007A:elliptic curve routines:EC_GROUP_check:invalid group order:crypto\ec\ec_check.c:107:
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-wrongorder.pem => 1
    ok 4
ok 7 - Check loading invalid parameters by ecparam with -check
# Subtest: Check loading invalid parameters by ecparam with -check_named
    1..4
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem => 255
    ok 1
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem => 255
    ok 2
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem
Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem => 255
    ok 3
checking elliptic curve parameters: failed
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-wrongorder.pem => 1
    ok 4
ok 8 - Check loading invalid parameters by ecparam with -check_named
# Subtest: Check loading invalid parameters by pkeyparam with -check
    1..4
Error reading parameters
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe pkeyparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem => 1
    ok 1
Error reading parameters
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe pkeyparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem => 1
    ok 2
Error reading parameters
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe pkeyparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem => 1
    ok 3
# Parameters are invalid
# Detailed error: invalid group order
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe pkeyparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-wrongorder.pem => 1
    ok 4
ok 9 - Check loading invalid parameters by pkeyparam with -check
# Subtest: Check ecparam does not change the parameter file on output
    1..200
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -out ecparam.tst -in ..\..\test\recipes\15-test_ecparam_data\valid\c2pnb163v1-named.pem => 0
    ok 1
```

**Comment by t8m** [comment]
@gv74 I do not see any crash in test_ecparam in the above log. Could you please try to at least isolate the concrete openssl ecparam invocation that crashes for you?

**Comment by gv74** [comment]
@t8m The first crash (the popup dialog above) is righ after 
`Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem`. 
I press "Close the program" on dialog.
`Could not read params of EC parameters from ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem` is printed on screen and the second popup is shown.
I close the second popup the following is printed on screen:
```
Can't spawn "cmd.exe": No such file or directory at ..\..\util\wrap.pl line 31.
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem => 255
    ok 1
```
And so on. 2 popups for each test. Exactly like fips tests. 

Command line for each crash, from process explorer (two consecutive times each):
```
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\c2pnb208w1-reducible.pem
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-nonprime.pem
C:\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe ecparam -noout -check_named -in ..\..\test\recipes\15-test_ecparam_data\invalid\nistp256-offcurve.pem

```

I do not have time for debugging right now to see exactly where the crash occur. Maybe next week if I get some free time.

**Comment by t8m** [comment]
> OK. I think I have pinpoint the problem in openssl.
> 
>     1. In self-test.c:277, (SELF_TEST_post()) the error is set::
>        `	ERR_raise(ERR_LIB_PROV, PROV_R_MODULE_INTEGRITY_FAILURE);`
>        The file and func are local variables in fips module.
> 
>     2. ERR_raise() macro will call err_set_debug(), err_local.h:52.
>        The file name and the function pointers are are assigned to ERR_STATE *es:
> 
> 
> ```
>     es->err_file[i] = file;
>     es->err_func[i] = fn;
> ```
> 
>     1. openssl execution will reach provider_core.c:540 that call:
>        `DSO_free(prov->module);`
>        This will **destroy** all memory used by fips module and now ERR_STATE *es will have two invalid pointers (`es->err_file` and `es->err_func`).
>        That I do not understand why the DSO_free() is executed since is guarded by #ifndef FIPS_MODULE.

The `#ifndef FIPS_MODULE` affects the fips provider only. Not the outside libcrypto that loads the provider and then unloads it.

>     2. openssl execution reach fipsinstall.c:510 (fipsinstall_main()) and will execute ERR_print_errors(bio_err); And, of course, since `es` refers an invalid memory, openssl will crash.

The ecparam crash fix is trivial. Unfortunately the fix for the test_fipsinstall is much more complicated. We would have to copy the filename/function to the error stack either via strdup or we would have to have some buffers for those preallocated. Neither of these two options are too appealing.

Actually there is another option - to clear the whole error stack or at least the file and function pointers in DSO_free() before the shared library is unloaded.

@levitte any preferred choice from the options above?

**Comment by t8m** [comment]
Fix for the ecparam test is in master now.

**Comment by t8m** [comment]
I've adjusted the subject of the issue to cover the remaining bug.

**Comment by t8m** [comment]
This was fixed when #14213 was merged.

**Comment by gv74** [comment]
I'm sorry but it's far from fixed. Still crashes wit alpha13 for:

```
..\..\apps\openssl.exe fipsinstall -out fips_fail.cnf -module ..\..\providers\fips.dll -provider_name fips -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 -section_name fips_sect -corrupt_desc SHA1

..\..\apps\openssl.exe fipsinstall -out fips_fail.cnf -module ..\..\providers\fips.dll -provider_name fips -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 -section_name fips_sect -corrupt_desc SHA3

..\..\apps\openssl.exe fipsinstall -out fips_fail.cnf -module ..\..\providers\fips.dll -provider_name fips -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 -section_name fips_sect -corrupt_desc CTR

..\..\apps\openssl.exe fipsinstall -out fips.cnf -module ..\..\providers\fips.dll -provider_name fips -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 -section_name fips_sect -corrupt_desc DH -corrupt_type KAT_KA

..\..\apps\openssl.exe fipsinstall -out fips.cnf -module ..\..\providers\fips.dll -provider_name fips -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 -section_name fips_sect -corrupt_desc DSA -corrupt_type KAT_Signature

..\..\apps\openssl.exe fipsinstall -out fips.cnf -module ..\..\providers\fips.dll -corrupt_desc RSA_Encrypt -corrupt_type KAT_AsymmetricCipher

```

Please re-open.

**Comment by rsbeckerca** [comment]
@paulidale Is it possible this is related to #14517 ?

**Comment by t8m** [comment]
@gv74 Then you should have opened a new issue. The problem is that we are mixing things here as the crash is a different one now. And I do not think this is related to #14517.

**Comment by gv74** [comment]
I opened an issue for a crash in test_fipsinstall. It's _still_ a crashing in test_fipsinstall! 
First issue test_fipsinstall. Second issue exactly the same test_fipsinstall. Are you for real? What other issue?

**Comment by t8m** [comment]
OK, unfortunately without knowing where it crashes the issue is not useful that much. It cannot crash at the same place as before, because that was fixed.

**Comment by gv74** [comment]
Call stack:

00007ffceda0277f()
[Inline Frame] libcrypto-3-x64.dll!init_thread_stop(void *) Line 315
	at D:\TEMP\openssl-ipm\release\openssl-3.0.0-alpha13\crypto\initthread.c(315)
libcrypto-3-x64.dll!OPENSSL_thread_stop() Line 229
	at D:\TEMP\openssl-ipm\release\openssl-3.0.0-alpha13\crypto\initthread.c(229)
[Inline Frame] libcrypto-3-x64.dll!OPENSSL_cleanup() Line 367
	at D:\TEMP\openssl-ipm\release\openssl-3.0.0-alpha13\crypto\init.c(367)
libcrypto-3-x64.dll!win32atexit() Line 81
	at D:\TEMP\openssl-ipm\release\openssl-3.0.0-alpha13\crypto\init.c(81)
[External Code]
openssl.exe!main(int argc, char * * argv) Line 307
	at D:\TEMP\openssl-ipm\release\openssl-3.0.0-alpha13\apps\openssl.c(307)
[External Code]

**Comment by rsbeckerca** [comment]
Just a question: is it possible that curr->hands has been cleaned up during termination and is no longer valid?
https://github.com/openssl/openssl/blob/0413b7bb9cbc63859972451e7a554171c2c1fddb/crypto/initthread.c#L315

**Comment by t8m** [comment]
> Call stack for
> ...

Thank you for providing that. This is very useful.

**Comment by mattcaswell** [comment]
> Just a question: is it possible that curr->handfn has been cleaned up during termination and is no longer valid?

`handfn` here could be a provider side function that is used to clean up some provider side data when a thread stops. The FIPS provider certainly uses this facility. If the FIPS module dll has been unloaded then handfn will no longer be valid and, if we attempt to use it, then we would see exactly this crash.

*However*, the same code that calls `DSO_free` to allow the removal of the module from memory, first calls `ossl_init_thread_deregister`:

https://github.com/openssl/openssl/blob/0413b7bb9cbc63859972451e7a554171c2c1fddb/crypto/provider_core.c#L341-L379

`ossl_init_thread_deregister` is a simple wrapper around `init_thread_deregister` which is supposed to iterate through all the handlers and remove any for the provider that is being unloaded:

https://github.com/openssl/openssl/blob/0413b7bb9cbc63859972451e7a554171c2c1fddb/crypto/initthread.c#L384-L432

So that, by the time `init_thread_stop` is called there should not be any handlers left in the list for any provider that has already been unloaded.

It looks to me like somewhere, somehow, that process is going wrong.

**Comment by beldmit** [comment]
Could be related to https://github.com/openssl/openssl/issues/9581?

**Comment by gv74** [comment]
This patch fix the crash for me. Not sure why in the second call for `init_thread_stop(...)`  `curr->arg` is `NULL`.

```
--- openssl-3.0.0-alpha13/crypto/initthread.c.orig      2021-03-11 15:47:00.000000000 +0200
+++ openssl-3.0.0-alpha13/crypto/initthread.c   2021-03-12 19:27:46.006947300 +0200
@@ -312,7 +312,8 @@
             curr = curr->next;
             continue;
         }
-        curr->handfn(curr->arg);
+        if (curr->arg)
+            curr->handfn(curr->arg);
         if (prev == NULL)
             *hands = curr->next;
         else

```

**Comment by mattcaswell** [comment]
> Not sure why in the second call for init_thread_stop(...) curr->arg is NULL.

Is `handfn` also NULL? Or if not I wonder if the debugger can tell you what function it is pointing at?

**Comment by gv74** [comment]
```
at D:\TEMP\openssl-ipm\debug\openssl-3.0.0-alpha13\crypto\initthread.c(229)
```
`hands` have the value from attached image. First `handfn` seems to be invalid.

**Comment by gv74** [comment]
![hands](https://user-images.githubusercontent.com/74062284/110980816-2b352600-835e-11eb-877c-29c7759b83b3.png)

**Comment by gv74** [comment]
The function reffered by the invalid handfn is `ossl_ctx_thread_stop`:
`0x0000022f27a988c0 {0x0000022f27b76060 {index=0x0000022f27b45ac0 arg=0x0000000000000000 handfn=0x00007ffce559277f {fips.dll!ossl_ctx_thread_stop} ...}}`

`handfn` become invalid after `DSO_free()` call (provider-core.c:560). More exactly in file dso_win32.c:148 when  `FreeLibrary()` is called from `win32_unload()`.

**Comment by mattcaswell** [comment]
Aha!!!!

> handfn become invalid after DSO_free() call (provider-core.c:560)

This was the clue I needed! I think I now understand what is going on. Normally `DSO_free()` gets called in `ossl_provider_free()` in the snippet of code I posted above. In that snippet we call `ossl_init_thread_deregister()` prior to to calling `DSO_free()` in order to remove all the thread handlers from the provider so that we avoid this exact problem. But line 560 that you quote above is the *failure* path after we have unsuccessfully attempted to initialise a provider, i.e. the `init_function` call has failed. But in spite of the fact it has failed it has already registered thread handlers - which we are not clearing up in this failure path. We probably need to call `ossl_init_thread_deregister()` in that failure path too.

**Comment by mattcaswell** [comment]
Unfortunately I am unable to reproduce this problem at all. On my windows environment everything works perfectly. I believe there is a race going on with the OS to see whether the dll gets unloaded prior to the thread clean up handlers being called or not.

Nonetheless I believe I have a fix. @gv74 would you be able to test out the fix in #14576 and see if it works for you?

**Comment by gv74** [comment]
> Unfortunately I am unable to reproduce this problem at all. On my windows environment everything works perfectly.

Strange, really strange. What compiler do you use? I have Visual Studio 2019 (16.9.1) on Windows Server 2016 (1607).

> Nonetheless I believe I have a fix. @gv74 would you be able to test out the fix in #14576 and see if it works for you?

After applying your fix, openssl does not crash anymore during test_fipsinstall test.

Thank you. Also, thanks everyone else who worked on this issue.
