### ISSUE TITLE
3.0.0 Alpha13 Broken on NonStop x86

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#14517]
The following result occurs at commit 6bbff162f1. This is new compared with alpha12.

```
( SRCTOP=. \
  BLDTOP=. \
  PERL="perl" \
  FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
  EXE_EXT= \
  perl ./test/run_tests.pl  )
01-test_abort.t .................... ok
01-test_fipsmodule_cnf.t ...........
version not found
VERIFY FAILED
00000000:error:0700006C:configuration file routines:NCONF_get_string:no value:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_lib.c:282:group=fips_sect name=install-version
../../util/wrap.pl ../../apps/openssl fipsinstall -in ../../providers/fipsmodule.cnf -module ../../providers/fips.so -verify => 1
not ok 1 - fipsinstall verify
```

**Comment by rsbeckerca** [comment]
This problem is not isolated to FIPS. The whole test log is attached. I'm really not sure where to start - the number of failed tests is daunting. This build was done in a clean directory (`git clean -dxf`/`make clean` with the same results).

[openssl-3.0.0-alpha13-nonstop.log](https://github.com/openssl/openssl/files/6126692/openssl-3.0.0-alpha13-nonstop.log)

**Comment by rsbeckerca** [comment]
A little more - other than not having FIPS on Itanium, all tests pass there, but not on the x86 NonStop variant (which is Big Endian) where a significant number of non-FIPS tests fail. I hope that particular confusion has not recurred.

**Comment by rsbeckerca** [comment]
I'm going to use `git bisect` to find where this broke.

**Comment by paulidale** [comment]
At a guess, the FIPS install broke which cascades all over the place.

Try: `make TESTS=test_fipsmodule_cnf V=1 test`

**Comment by rsbeckerca** [comment]
> 
> 
> At a guess, the FIPS install broke which cascades all over the place.
> 
> Try: `make TESTS=test_fipsmodule_cnf V=1 test`

Possible. I'm at commit 77e4ae58ea, which was bad (could not compile) because of 
```
crypto/evp/mac_lib.c
      return ctx->meth->init(ctx->data, key, keylen, params);
                                        ^
"/home/ituglib/randall/openssl-3.0/crypto/evp/mac_lib.c", line 111: error(229):
          too many arguments in function call
```
which should never have been merged. Skipping it and moving closer to HEAD in hope that that was resolved.

**Comment by paulidale** [comment]
It was merged as part of a block, the end will compile okay.

**Comment by levitte** [comment]
I just ran a test on s390x, just to see if I could trigger test errors there (on the basis that it's also a big endian system).  I got a failure with 80-test_cmp_http.t, but that was it, so I'm unable to help much...

**Comment by rsbeckerca** [comment]
Most of the tests (50-ish) failed because of:
`error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found`

90-test_sslapi failed to load the config, which I suspect is the same cause _without reporting the above error._ So this does seem to be all about FIPS.

The V=1 test result is:
```
01-test_fipsmodule_cnf.t ..
# The results of this test will end up in test-runs/test_fipsmodule
1..1
version not found
VERIFY FAILED
00000000:error:0700006C:configuration file routines:NCONF_get_string:no value:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_lib.c:282:group=fips_sect name=install-version
../../util/wrap.pl ../../apps/openssl fipsinstall -in ../../providers/fipsmodule.cnf -module ../../providers/fips.so -verify => 1
not ok 1 - fipsinstall verify
```

**Comment by rsbeckerca** [comment]
After reconfiguring the no-fips option, and making, I still get errors relating to fips. I'm thinking there is another issue buried in this one where you have to clean up before make after a reconfigure. Still, would rather focus on getting fips to work again.

**Comment by rsbeckerca** [comment]
Even with a clean configure/build (after `git clean -dxf`), 15-test_rsaoaep and 90-test_fipsload both run and fail.
```
15-test_rsaoaep.t .................. 1/?
Using configuration from ../../test/fips-and-base.cnf
Error configuring OpenSSL modules
00000000:error:80000FA2:system library:process_include:No such file or directory:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_def.c:771:calling stat(/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf)
00000000:error:07800069:common libcrypto routines:provider_conf_load:provider section error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found
00000000:error:0700006D:configuration file routines:module_run:module initialization error:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:242:module=providers, value=provider_sect retcode=-1
../../util/wrap.pl ../../apps/openssl pkeyutl -provider-path ../../providers -config ../../test/fips-and-base.cnf -encrypt -in ../../test/recipes/15-test_rsaoaep_data/plain_text -inkey ../../test/testrsa2048.pem -pkeyopt 'pad-mode:oaep' -pkeyopt 'oaep-label:123' -pkeyopt 'digest:sha1' -pkeyopt 'mgf1-digest:sha1' -out enc1.bin => 1
not ok 2 - RSA OAEP Encryption
# ------------------------------------------------------------------------------
Using configuration from ../../test/fips-and-base.cnf
Error configuring OpenSSL modules
00000000:error:80000FA2:system library:process_include:No such file or directory:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_def.c:771:calling stat(/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf)
00000000:error:07800069:common libcrypto routines:provider_conf_load:provider section error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found
00000000:error:0700006D:configuration file routines:module_run:module initialization error:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:242:module=providers, value=provider_sect retcode=-1
../../util/wrap.pl ../../apps/openssl pkeyutl -provider-path ../../providers -config ../../test/fips-and-base.cnf -decrypt -inkey ../../test/testrsa2048.pem -pkeyopt 'pad-mode:oaep' -pkeyopt 'oaep-label:123' -pkeyopt 'digest:sha1' -pkeyopt 'mgf1-digest:sha1' -in enc1.bin -out dec1.txt => 1
not ok 4 - RSA OAEP Decryption
15-test_rsaoaep.t .................. 4/? ---------------------------------------
Using configuration from ../../test/fips-and-base.cnf
Error configuring OpenSSL modules
00000000:error:80000FA2:system library:process_include:No such file or directory:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_def.c:771:calling stat(/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf)
00000000:error:07800069:common libcrypto routines:provider_conf_load:provider section error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found
00000000:error:0700006D:configuration file routines:module_run:module initialization error:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:242:module=providers, value=provider_sect retcode=-1
../../util/wrap.pl ../../apps/openssl pkeyutl -provider-path ../../providers -config ../../test/fips-and-base.cnf -encrypt -in ../../test/recipes/15-test_rsaoaep_data/plain_text -inkey ../../test/testrsa2048.pem -pkeyopt 'pad-mode:oaep' -pkeyopt 'oaep-label:123' -pkeyopt 'digest:sha1' -pkeyopt 'mgf1-digest:sha1' -out enc2.bin => 1
not ok 7 - RSA OAEP Encryption should generate different encrypted data
# ------------------------------------------------------------------------------
#   Failed test 'RSA OAEP Encryption should generate different encrypted data'
#   at test/recipes/15-test_rsaoaep.t line 116.
Using configuration from ../../test/fips-and-base.cnf
Error configuring OpenSSL modules
00000000:error:80000FA2:system library:process_include:No such file or directory:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_def.c:771:calling stat(/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf)
00000000:error:07800069:common libcrypto routines:provider_conf_load:provider section error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found
00000000:error:0700006D:configuration file routines:module_run:module initialization error:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:242:module=providers, value=provider_sect retcode=-1
../../util/wrap.pl ../../apps/openssl pkeyutl -provider-path ../../providers -config ../../test/fips-and-base.cnf -decrypt -inkey ../../test/testrsa2048.pem -pkeyopt 'pad-mode:oaep' -pkeyopt 'oaep-label:123' -in enc2.bin -out dec2.txt => 1
not ok 8 - RSA OAEP Decryption with default digests
15-test_rsaoaep.t .................. 8/? ---------------------------------------
#   Failed test 'RSA OAEP Decryption with default digests'
#   at test/recipes/15-test_rsaoaep.t line 129.
Using configuration from ../../test/fips-and-base.cnf
Error configuring OpenSSL modules
00000000:error:80000FA2:system library:process_include:No such file or directory:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_def.c:771:calling stat(/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf)
00000000:error:07800069:common libcrypto routines:provider_conf_load:provider section error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found
00000000:error:0700006D:configuration file routines:module_run:module initialization error:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:242:module=providers, value=provider_sect retcode=-1
../../util/wrap.pl ../../apps/openssl pkeyutl -provider-path ../../providers -config ../../test/fips-and-base.cnf -encrypt -in ../../test/recipes/15-test_rsaoaep_data/plain_text -inkey ../../test/testrsa2048.pem -pkeyopt 'pad-mode:oaep' -pkeyopt 'oaep-label:123' -out enc3.bin => 1
not ok 9 - RSA OAEP Encryption with default digests
# ------------------------------------------------------------------------------
#   Failed test 'RSA OAEP Encryption with default digests'
#   at test/recipes/15-test_rsaoaep.t line 140.
Using configuration from ../../test/fips-and-base.cnf
Error configuring OpenSSL modules
00000000:error:80000FA2:system library:process_include:No such file or directory:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_def.c:771:calling stat(/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf)
00000000:error:07800069:common libcrypto routines:provider_conf_load:provider section error:/home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:90:section=fips_sect not found
00000000:error:0700006D:configuration file routines:module_run:module initialization error:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:242:module=providers, value=provider_sect retcode=-1
../../util/wrap.pl ../../apps/openssl pkeyutl -provider-path ../../providers -config ../../test/fips-and-base.cnf -decrypt -inkey ../../test/testrsa2048.pem -pkeyopt 'pad-mode:oaep' -pkeyopt 'oaep-label:123' -pkeyopt 'digest:sha1' -pkeyopt 'mgf1-digest:sha1' -in enc3.bin -out dec3.txt => 1
not ok 10 - RSA OAEP Decryption with explicit default digests
# ------------------------------------------------------------------------------
#   Failed test 'RSA OAEP Decryption with explicit default digests'
#   at test/recipes/15-test_rsaoaep.t line 150.

90-test_fipsload.t .................
../../util/wrap.pl ../../test/moduleloadtest ../../providers/fips.so OSSL_provider_init => 1
not ok 1 - trying to load ../../providers/fips.so in its own
90-test_fipsload.t ................. 1/? ---------------------------------------
#   Failed test 'trying to load ../../providers/fips.so in its own'
#   at test/recipes/90-test_fipsload.t line 29.
```

not sure how to disable these.

**Comment by rsbeckerca** [comment]
as of commit 91bd45eb9a

```
Test Summary Report
-------------------
01-test_fipsmodule_cnf.t         (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
15-test_gendsa.t                 (Wstat: 512 Tests: 13 Failed: 2)
  Failed tests:  12-13
  Non-zero exit status: 2
15-test_genrsa.t                 (Wstat: 256 Tests: 14 Failed: 1)
  Failed test:  14
  Non-zero exit status: 1
15-test_rsaoaep.t                (Wstat: 1536 Tests: 10 Failed: 6)
  Failed tests:  2, 4, 7-10
  Non-zero exit status: 6
20-test_cli_fips.t               (Wstat: 768 Tests: 11 Failed: 3)
  Failed tests:  9-11
  Non-zero exit status: 3
30-test_acvp.t                   (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
30-test_defltfips.t              (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
30-test_evp.t                    (Wstat: 6656 Tests: 89 Failed: 26)
  Failed tests:  27-52
  Non-zero exit status: 26
30-test_evp_fetch_prov.t         (Wstat: 10240 Tests: 53 Failed: 40)
  Failed tests:  8-27, 34-53
  Non-zero exit status: 40
30-test_evp_libctx.t             (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
30-test_provider_status.t        (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
65-test_cmp_msg.t                (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
65-test_cmp_protect.t            (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
65-test_cmp_server.t             (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
65-test_cmp_vfy.t                (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
80-test_cms.t                    (Wstat: 1792 Tests: 10 Failed: 7)
  Failed tests:  1-5, 8, 10
  Non-zero exit status: 7
80-test_ssl_new.t                (Wstat: 7168 Tests: 30 Failed: 28)
  Failed tests:  1-21, 23-28, 30
  Non-zero exit status: 28
80-test_ssl_old.t                (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  7
  Non-zero exit status: 1
90-test_sslapi.t                 (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
90-test_threads.t                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=233, Tests=3228, 2330 wallclock secs (12.35 usr  0.00 sys + 1119.76 cusr 13.45 csys = 1145.57 CPU)
Result: FAIL
```
All appear to be FIPS related.

**Comment by paulidale** [comment]
Yep, figure out what's wrong with the first test and the rest will work.

**Comment by rsbeckerca** [comment]
Any pointers? I don't know the FIPS code.

**Comment by paulidale** [comment]
Run the test individually and look at the errors?
At least that's what I do.

**Comment by rsbeckerca** [comment]
Well, the version not found message is a bit of a clue, but resolving it is s different matter.

**Comment by paulidale** [comment]
Failure of the module signature???

**Comment by rsbeckerca** [comment]
That's what it was last time

**Comment by levitte** [comment]
So, perhaps a few question would clear things up...

1.  What happens if you do this:  `rm providers/fipsmodule.cnf; make providers/fipsmodule.cnf`
2.  Does `providers/fipsmodule.cnf` exist? Is that the same as  `/home/ituglib/randall/openssl-3.0/providers/fipsmodule.cnf`?
3.  Please show us the contents of `providers/fipsmodule.cnf` (it's a text file, so...).
4.  When you do `make test`, do you see the output start with something like this?

    ``` console
    $ make test
    ./util/wrap.pl apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - > providers/fipsmodule.cnf
    HMAC : (Module_Integrity) : Pass
    SHA1 : (KAT_Digest) : Pass
    SHA2 : (KAT_Digest) : Pass
    SHA3 : (KAT_Digest) : Pass
    TDES : (KAT_Cipher) : Pass
    AES_GCM : (KAT_Cipher) : Pass
    RSA : (KAT_Signature) : RNG : (Continuous_RNG_Test) : Pass
    Pass
    ECDSA : (KAT_Signature) : Pass
    DSA : (KAT_Signature) : Pass
    TLS12_PRF : (KAT_KDF) : Pass
    PBKDF2 : (KAT_KDF) : Pass
    SSHKDF : (KAT_KDF) : Pass
    KBKDF : (KAT_KDF) : Pass
    HKDF : (KAT_KDF) : Pass
    SSKDF : (KAT_KDF) : Pass
    X963KDF : (KAT_KDF) : Pass
    X942KDF : (KAT_KDF) : Pass
    HASH : (DRBG) : Pass
    CTR : (DRBG) : Pass
    HMAC : (DRBG) : Pass
    DH : (KAT_KA) : Pass
    ECDH : (KAT_KA) : Pass
    RSA_Encrypt : (KAT_AsymmetricCipher) : Pass
    RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
    RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
    INSTALL PASSED
    make depend && make _tests
    make[1]: Entering directory '/home/levitte/gitwrk/openssl.net/official/_build'
    make[1]: Leaving directory '/home/levitte/gitwrk/openssl.net/official/_build'
    make[1]: Entering directory '/home/levitte/gitwrk/openssl.net/official/_build'
    ( SRCTOP=../master \
      BLDTOP=. \
      PERL="/usr/bin/perl" \
      FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
      EXE_EXT= \
      /usr/bin/perl ../master/test/run_tests.pl  )
    01-test_abort.t .................... ok   
    ```

**Comment by levitte** [comment]
I finally got the same type of errors on s390x.

@rsbecker, you didn't by any chance use parallel make for build+test in one command, i.e. something like `make -j4 test`?  I haven't looked closely yet, but I'm having a hunch that we messed up parallelism...

**Comment by rsbeckerca** [comment]
providers/fipsmodule.cnf is not being built as part of the standard `make` or `make test`. If I use make `providers/fipsprovider.cnf`, the file is created but it is empty.

I'm not using parallel make at all. That opens up a whole bunch of timing problems on the MPP platform.

**Comment by linlinthu8679** [comment]
> The following result occurs at commit [6bbff16](https://github.com/openssl/openssl/commit/6bbff162f1d72ed52d705c4c146cd3152ef4648c). This is new compared with alpha12.
> 
> ```
> ( SRCTOP=. \
>   BLDTOP=. \
>   PERL="perl" \
>   FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
>   EXE_EXT= \
>   perl ./test/run_tests.pl  )
> 01-test_abort.t .................... ok
> 01-test_fipsmodule_cnf.t ...........
> version not found
> VERIFY FAILED
> 00000000:error:0700006C:configuration file routines:NCONF_get_string:no value:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_lib.c:282:group=fips_sect name=install-version
> ../../util/wrap.pl ../../apps/openssl fipsinstall -in ../../providers/fipsmodule.cnf -module ../../providers/fips.so -verify => 1
> not ok 1 - fipsinstall verify
> ```

**Comment by linlinthu8679** [comment]
thanks

**Comment by linlinthu8679** [comment]
#14449

**Comment by levitte** [comment]
Er, @rsbecker, is that with or without `no-fips`?  Without it, `make test` should make providers/fipsmodule.cnf.  WIth `no-fips`, no such file is made, of course, and if there are test recipes that still try to use it, then they should be fixed.

**Comment by rsbeckerca** [comment]
@linlinthu8679 #14449 does not fix this situation completely.
The fix for #14517 does not correct the problem. providers/fipsmodule.cnf is still empty despite the following:

```
$ make providers/fipsmodule.cnf
Makefile:2346: warning: overriding recipe for target 'libcrypto.so'
Makefile:2341: warning: ignoring old recipe for target 'libcrypto.so'
Makefile:7616: warning: overriding recipe for target 'libssl.so'
Makefile:7612: warning: ignoring old recipe for target 'libssl.so'
make: Circular libcrypto.so <- libcrypto.so dependency dropped.
make: Circular libssl.so <- libssl.so dependency dropped.
./util/wrap.pl apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - > providers/fipsmodule.cnf
HMAC : (Module_Integrity) : Pass
SHA1 : (KAT_Digest) : Pass
SHA2 : (KAT_Digest) : Pass
SHA3 : (KAT_Digest) : Pass
TDES : (KAT_Cipher) : Pass
AES_GCM : (KAT_Cipher) : Pass
RSA : (KAT_Signature) : RNG : (Continuous_RNG_Test) : Pass
Pass
ECDSA : (KAT_Signature) : Pass
DSA : (KAT_Signature) : Pass
TLS12_PRF : (KAT_KDF) : Pass
PBKDF2 : (KAT_KDF) : Pass
SSHKDF : (KAT_KDF) : Pass
KBKDF : (KAT_KDF) : Pass
HKDF : (KAT_KDF) : Pass
SSKDF : (KAT_KDF) : Pass
X963KDF : (KAT_KDF) : Pass
X942KDF : (KAT_KDF) : Pass
HASH : (DRBG) : Pass
CTR : (DRBG) : Pass
HMAC : (DRBG) : Pass
DH : (KAT_KA) : Pass
ECDH : (KAT_KA) : Pass
RSA_Encrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
INSTALL PASSED
```
FIPS continues to fail to load. providers/fipsmodule.cnf is still empty after the above and is not placed elsewhere. Resulting in:
```
$ make TESTS=test_fipsmodule_cnf V=1 test
Makefile:2346: warning: overriding recipe for target 'libcrypto.so'
Makefile:2341: warning: ignoring old recipe for target 'libcrypto.so'
Makefile:7616: warning: overriding recipe for target 'libssl.so'
Makefile:7612: warning: ignoring old recipe for target 'libssl.so'
make: Circular libcrypto.so <- libcrypto.so dependency dropped.
make: Circular libssl.so <- libssl.so dependency dropped.
make depend && make _tests
make[1]: Entering directory '/home/ituglib/randall/openssl-3.0'
Makefile:2346: warning: overriding recipe for target 'libcrypto.so'
Makefile:2341: warning: ignoring old recipe for target 'libcrypto.so'
Makefile:7616: warning: overriding recipe for target 'libssl.so'
Makefile:7612: warning: ignoring old recipe for target 'libssl.so'
make[1]: Leaving directory '/home/ituglib/randall/openssl-3.0'
make[1]: Entering directory '/home/ituglib/randall/openssl-3.0'
Makefile:2346: warning: overriding recipe for target 'libcrypto.so'
Makefile:2341: warning: ignoring old recipe for target 'libcrypto.so'
Makefile:7616: warning: overriding recipe for target 'libssl.so'
Makefile:7612: warning: ignoring old recipe for target 'libssl.so'
make[1]: Circular libcrypto.so <- libcrypto.so dependency dropped.
make[1]: Circular libssl.so <- libssl.so dependency dropped.
( SRCTOP=. \
  BLDTOP=. \
  PERL="perl" \
  FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
  EXE_EXT= \
  perl ./test/run_tests.pl test_fipsmodule_cnf )
01-test_fipsmodule_cnf.t ..
# The results of this test will end up in test-runs/test_fipsmodule
1..1
version not found
VERIFY FAILED
00000000:error:0700006C:configuration file routines:NCONF_get_string:no value:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_lib.c:282:group=fips_sect name=install-version
../../util/wrap.pl ../../apps/openssl fipsinstall -in ../../providers/fipsmodule.cnf -module ../../providers/fips.so -verify => 1
not ok 1 - fipsinstall verify

#   Failed test 'fipsinstall verify'
#   at test/recipes/01-test_fipsmodule_cnf.t line 35.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
01-test_fipsmodule_cnf.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.45 cusr  0.00 csys =  0.47 CPU)
Result: FAIL
Makefile:1445: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/ituglib/randall/openssl-3.0'
Makefile:1443: recipe for target 'tests' failed
make: *** [tests] Error 2
```

**Comment by rsbeckerca** [comment]
No-fips is not specified on the config.

**Comment by rsbeckerca** [comment]
Currently at commit d8a809db4b. Our configure is:
`./Configure nonstop-nsx_64 --prefix=/usr/local-ssl3.0 --openssldir=/usr/local-ssl3.0/ssl --with-rand-seed=rdcpu`
resulting in the following configuration.
```

Command line (with current working directory = .):

    perl ./Configure nonstop-nsx_64 --prefix=/usr/local-ssl3.0 --openssldir=/usr/local-ssl3.0/ssl --with-rand-seed=rdcpu

Perl information:

    perl
    5.26.3 for NSV-D-nonstop_kernel

Enabled features:

    acvp_tests
    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    egd
    engine
    err
    filenames
    fips
    fips-securitychecks
    gost
    idea
    legacy
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    padlockeng
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    asm                 [no asm_arch]    OPENSSL_NO_ASM
    buildtest-c++       [default]
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    ktls                [default]        OPENSSL_NO_KTLS
    makedepend          [unavailable]
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    ssl-trace           [default]        OPENSSL_NO_SSL_TRACE
    threads             [config]
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]
    zlib-dynamic        [default]
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "c99",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    bn_ops => "SIXTY_FOUR_BIT",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-g -O2 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/x -Wsystype=oss -Wlp64 -WIEEE_float",
    cppflags => "",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "OPENSSL_VPROC=\$(OPENSSL_VPROC)", "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED=1", "_TANDEM_SOURCE", "B_ENDIAN", "_TANDEM_ARCH=3" ],
    disable => [ "threads" ],
    dso_scheme => "DLFCN",
    enable => [ "egd" ],
    ex_libs => "-lrld",
    includes => [  ],
    lflags => "-Wxld=\"-set systype oss\" -Wxld=\"-set data_model lp64\" -Wxld=\"-set floattype ieee_float\"",
    lib_cflags => "",
    lib_cppflags => "",
    lib_defines => [  ],
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "-Wshared",
    perl => "/usr/bin/perl",
    perl_platform => "Unix",
    shared_argfileflag => "-Wxld_obey=",
    shared_cflag => "",
    shared_defflag => "-Wxld_obey=",
    shared_defines => [  ],
    shared_extension => ".so",
    shared_ldflag => "-Wshared",
    shared_rcflag => "",
    shared_target => "nonstop-shared",
    sys_id => "TANDEM",
    thread_defines => [  ],
    thread_scheme => "(unknown)",
    unistd => "<unistd.h>",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = qc
    CC              = c99
    CFLAGS          =
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
```

**Comment by levitte** [comment]
Wait, when you answered my questions, were you still in the middle of a bisect?  I'm really only interested in the answer at the alpha13 tag, or current master HEAD

**Comment by rsbeckerca** [comment]
> 
> 
> Wait, when you answered my questions, were you still in the middle of a bisect? I'm really only interested in the answer at the alpha13 tag, or current master HEAD

No, I aborted the bisect. It wasn't getting me anywhere. This is all (today's messages) based on a pull from an hour ago.

**Comment by linlinthu8679** [comment]
> အောက်ပါရလဒ်သည် commit [6bbff16](https://github.com/openssl/openssl/commit/6bbff162f1d72ed52d705c4c146cd3152ef4648c) တွင်ဖြစ်ပေါ်သည် ။ ဤသည် alpha12 နှင့်နှိုင်းယှဉ်လျှင်အသစ်ဖြစ်သည်။
> 
> ```
> ( SRCTOP=. \
>   BLDTOP=. \
>   PERL="perl" \
>   FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
>   EXE_EXT= \
>   perl ./test/run_tests.pl  )
> 01-test_abort.t .................... ok
> 01-test_fipsmodule_cnf.t ...........
> version not found
> VERIFY FAILED
> 00000000:error:0700006C:configuration file routines:NCONF_get_string:no value:/home/ituglib/randall/openssl-3.0/crypto/conf/conf_lib.c:282:group=fips_sect name=install-version
> ../../util/wrap.pl ../../apps/openssl fipsinstall -in ../../providers/fipsmodule.cnf -module ../../providers/fips.so -verify => 1
> not ok 1 - fipsinstall verify
> ```

**Comment by levitte** [comment]
Ok.  So, you see the fipsinstall command line up the when you test...  you can also produce it manually, like this:

``` console
$ rm providers/fipsmodule.cnf
$ make providers/fipsmodule.cnf
```

Is it still ending up empty, even though the command appears successful?  If so, we might need your help debugging what's going on...

**Comment by rsbeckerca** [comment]
> 
> 
> Ok. So, you see the fipsinstall command line up there when you test... you can also produce it manually, like this:
> 
> ```
> $ rm providers/fipsmodule.cnf
> $ make providers/fipsmodule.cnf
> ```
> 
> Is it still ending up empty, even though the command appears successful? If so, we might need your help debugging what's going on...

Still empty. Where should I put gdb and breakpoints?

**Comment by rsbeckerca** [comment]
In `crypto/conf/conf_mod.c`, `default_config_file = "/usr/local-ssl3.0/ssl/openssl.cnf"`. That does not seem to make sense, since we never did an install of OpenSSL 3.0. That file doesn't exist.

**Comment by levitte** [comment]
`INSTALL PASSED` indicates that `write_config_fips_section()`, in `apps/fipsinstall.c`, was called and succeeded.  It might be interesting to have a look at it and find out why it doesn't output anything...

**Comment by rsbeckerca** [comment]
I saw the `BIO_printf(out)` and `ret=1` being executed. I tried putting in a BIO_flush, but that did not seem to help. The code got down to `_dopr` with no trouble (`"activate = 1\n"`) was the first I/O. There were 8 in total, mostly `"%s = %s"` style except for the first one. The last mod time on the file is the same as the create time, which is suspicious as it appears that the writes never actually made it to disk.

**Comment by rsbeckerca** [comment]
I also tried putting a `BIO_flush` inside `BIO_printf`, but that did not help.

**Comment by rsbeckerca** [comment]
@levitte Any interest in my setting up a Zoom session to debug this together?

**Comment by rsbeckerca** [comment]
I can also use the output from `openssl ... -out - | tee providers/fipsmodule.cnf` and the contents are correct. Otherwise they are empty.

**Comment by rsbeckerca** [comment]
> 
> 
> Hmmm, the BIO out should be connected to stdout in this command:
> 
> ```
> ./util/wrap.pl apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - > providers/fipsmodule.cnf
> ```
> 
> Are you saying that's not quite the case?
> 
> As for bwrite_old, it's implemented as a bridge to call the newer write function... is that not happening?

If use the output from `openssl ... -out - | tee providers/fipsmodule.cnf` the contents of `providers/fipsmodule.cnf` are correct and I get 100% PASS. Using `openssl ... -out - >providers/fipsmodule.cnf` leaves that file empty. I am not seeing anything done by `bwrite_old` when I step in (actually gdb just steps over it), unlike `bwrite_conv`.

**Comment by rsbeckerca** [comment]
> 
> 
> > Hmmm, the BIO out should be connected to stdout in this command:
> > ```
> > ./util/wrap.pl apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - > providers/fipsmodule.cnf
> > ```
> > 
> > 
> > Are you saying that's not quite the case?
> > As for bwrite_old, it's implemented as a bridge to call the newer write function... is that not happening?
> 
> If I use `openssl ... -out - | tee providers/fipsmodule.cnf` the contents of `providers/fipsmodule.cnf` are correct and I get 100% PASS. Using `openssl ... -out - >providers/fipsmodule.cnf` leaves that file empty. I am not seeing anything done by `bwrite_old` when I step in (actually `gdb` just steps over it), unlike `bwrite_conv`.

I should also mention that this occurs without the perl wrapper. I can get this behaviour from a shell prompt directly, so we can exclude perl from being at fault.

**Comment by paulidale** [comment]
In effect you are saying that _|_ and _>_ are doing something different with the stdout of the openssl command.  Might this be something weird in NonStop?

_>_ will replace the file **before** the command is executed and if something fails it will leave a zero byte file.

What if you remove `providers/fipsmodule.cnf` and then run the command?

**Comment by rsbeckerca** [comment]
Same effect. Is BIO detecting the file type or calling fcntl or ioctl?

**Comment by paulidale** [comment]
They shouldn't be called.  BIOs are pretty basic wrappers over the underlying file/whatever.

**Comment by rsbeckerca** [comment]
> They shouldn't be called.  BIOs are pretty basic wrappers over the underlying file/whatever.

So why did this work at alpha 11? The OS did not change since then.

**Comment by levitte** [comment]
> So why did this work at alpha 11?

Because the command to generate it has change ever so slightly.  Earlier, it looked approximately like this:

```
./util/wrap.pl apps/openssl fipsinstall -out providers/fipsmodule.cnf -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect
```

now it looks like this:

```
./util/wrap.pl apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - > providers/fipsmodule.cnf
```

The latter is generated from a GENERATE statement in providers/build.info, which was modified recently (just before alpha13 was released).

There's really nothing weird with that command.  The output is supposed to go to stdout, and under normal Unix semantics, it doesn't matter if stdout is redirected to a file or to a pipe, it should look the same to `apps/openssl`.  It appears, though, that the semantics is different on NonStop, and the question is why.
Since the responsibility for setting that up normally belongs with the shell, I suspect that there's something weird going there, and I can only guess...:

-   The shell might be setting things up in a weird way, and we've encountered a corner case.  A distinct thing to look for is that redirecting to file or piping seem to differ somehow.
-   The shell might detect pipes and set those up properly, but otherwise do things Windows style and actually leave it to the application to do the right thing, such as parsing the command line for redirections and setting them up.  This is presumably handled by the setup code (often called crt0) before main() is called, and that code might be doing something weird...  another corner case.

I just looked through the BIO for known oddities, but they are platform specific (`_setmode()` and `setvbuf()` calls on Windows, for example) and shouldn't affect NonStop.

... and mind you, the weirdness might be perfectly legitimate, depending on OS specific details (as an anecdote, OpenVMS has the shell and the running program living in the same process, just different memory segments, and that leads to ...  interesting possibilities).  I know that Unix semantics can be challenging when the target OS doesn't work quite the same way.

**Comment by rsbeckerca** [comment]
I have never seen a pipe issue impacting stdout like this on platform (in 27 years). Going through sockets, yes, there are some default setup issues. I'll try to fine that one.

Is there anything I can test in isolation? The platform support team will need a smaller condition - I don't have the crt0 equivalent source code.

**Comment by rsbeckerca** [comment]
One hypothetical difference: buffering. A non-file pipe will tend to flush on LF, while a file pipe will wait for whatever buffer limit exists. If a DLL unloads badly(?) before the runtime flush, the output can be lost. I've seen this happen similarly when a program bypasses exit code and uses a low level abend.

**Comment by levitte** [comment]
> If a DLL unloads badly(?) before the runtime flush

Hmmm, I believe that `apps/fipsinstall.c` does the printing on its own, and since it's essentially passing everything to stdout (via BIO, but still, there shouldn't be any buffering performed by the BIO code, it should all be passed directly to stdio).  The only DLLs involved with that would be libcrypto, and the C RTL everything is linked with, and since those are linked at build time (right?), the takedown is after main() returns, which is outside our control.  As far as I know, we use normal exit() / return mechanisms in our main...

**Comment by levitte** [comment]
> Is there anything I can test in isolation?

``` console
$ echo foo | ./util/wrap.pl apps/openssl dgst -sha1 > foo.hashed
```

If `foo.hashed` has contents (one line of text), then we know we need to zero in on what fipsinstall does.  Otherwise, we know this is a general stdout issue.

**Comment by rsbeckerca** [comment]
> 
> 
> > Is there anything I can test in isolation?
> 
> ```
> $ echo foo | ./util/wrap.pl apps/openssl dgst -sha1 > foo.hashed
> ```
> 
> If `foo.hashed` has contents (one line of text), then we know we need to zero in on what fipsinstall does. Otherwise, we know this is a general stdout issue.

The result in foo.hashed is: `SHA1(stdin)= f1d2d2f924e986ac86fdf7b36c94bcdf32beec15`

So fipsinstall it is.

**Comment by rsbeckerca** [comment]
Side question on this. Going back to 2015, we found a gnulib.c problem with poll/select where the pfds structure was not being initialized correctly. Basically, revents has to be set to 0 explicitly in order for post-select processing to work. We found this in git actually after a CPU memory dump of the kernel but that was in a hang situation. This is obviously different but I don't see any use of revents associated with any select in OpenSSL at all. Just wondering if there is a common history of this. It's something we look for when there is random weirdness.

**Comment by rsbeckerca** [comment]
@levitte I put a `BIO_flush` in `BIO_close` and was able to get `providers/fipsmodules.cnf` constructed. So this appears to be a flush issue. I don't think this is the correct fix, but for debugging...
```
diff --git a/crypto/bio/bio_lib.c b/crypto/bio/bio_lib.c
index 6d360b62ed..635cfaa152 100644
--- a/crypto/bio/bio_lib.c
+++ b/crypto/bio/bio_lib.c
@@ -692,6 +692,7 @@ void BIO_free_all(BIO *bio)
         b = bio;
         ref = b->references;
         bio = bio->next_bio;
+        BIO_flush(b);
         BIO_free(b);
         /* Since ref count > 1, don't free anyone else. */
         if (ref > 1)
```

**Comment by levitte** [comment]
It could be that we should flush in BIO_free(). I for one can't see anything wrong with that.

**Comment by rsbeckerca** [comment]
> It could be that we should flush in BIO_free(). I for one can't see anything wrong with that. 

I can put the PR together in about an hour.

**Comment by rsbeckerca** [comment]
I think I'm missing something regarding the BIO infrastructure:
```
include/openssl/bio.h:553:34: error: value computed is not used [-Werror=unused-value]
  553 | # define BIO_flush(b)            (int)BIO_ctrl(b,BIO_CTRL_FLUSH,0,NULL)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
crypto/bio/bio_lib.c:117:5: note: in expansion of macro 'BIO_flush'
  117 |     BIO_flush(a);
      |     ^~~~~~~~~
```

**Comment by rsbeckerca** [comment]
I can't push right now. It looks like the HEAD commit ee067bc066 is bad.
```
**** ERROR **** [1210]:
   providers/libnonfips.a(libnonfips-lib-rand_unix.o): In function
   `ossl_pool_acquire_entropy':
   libnonfips-lib-rand_unix.o(.text+0x6d): unresolved reference to
   ossl_prov_acquire_entropy_from_cpu.
```

**Comment by rsbeckerca** [comment]
I'm feeling a bit like the rug got pulled out from under me on this one.

**Comment by levitte** [comment]
> I think I'm missing something regarding the BIO infrastructure:

That's the compiler complaining that the line isn't looking at the returned value.  It's pretty easy to shut the compiler up, though:

``` C
    (void)BIO_flush(a);
```

**Comment by rsbeckerca** [comment]
I'm going to try this based on alpha-13, which I know was broken. After that, I think I might need to open a separate issue regarding the undefined external.

**Comment by levitte** [comment]
> I can't push right now. It looks like the HEAD commit ee067bc is bad.

Here's the patch to fix it:

``` diff
diff --git a/providers/implementations/rands/seeding/rand_cpu_x86.c b/providers/implementations/rands/seeding/rand_cpu_x86.c
index 0bdf1c302f..39da74e293 100644
--- a/providers/implementations/rands/seeding/rand_cpu_x86.c
+++ b/providers/implementations/rands/seeding/rand_cpu_x86.c
@@ -35,7 +35,7 @@ static size_t get_hardware_random_value(unsigned char *buf, size_t len);
  * Returns the total entropy count, if it exceeds the requested
  * entropy count. Otherwise, returns an entropy count of 0.
  */
-size_t prov_acquire_entropy_from_cpu(RAND_POOL *pool)
+size_t ossl_prov_acquire_entropy_from_cpu(RAND_POOL *pool)
 {
     size_t bytes_needed;
     unsigned char *buffer;
```

**Comment by rsbeckerca** [comment]
> 
> 
> > I can't push right now. It looks like the HEAD commit [ee067bc](https://github.com/openssl/openssl/commit/ee067bc066ccc21462a1a489f8f1314c7207c01f) is bad.
> 
> Here's the patch to fix it:
> 
> ```diff
> diff --git a/providers/implementations/rands/seeding/rand_cpu_x86.c b/providers/implementations/rands/seeding/rand_cpu_x86.c
> index 0bdf1c302f..39da74e293 100644
> --- a/providers/implementations/rands/seeding/rand_cpu_x86.c
> +++ b/providers/implementations/rands/seeding/rand_cpu_x86.c
> @@ -35,7 +35,7 @@ static size_t get_hardware_random_value(unsigned char *buf, size_t len);
>   * Returns the total entropy count, if it exceeds the requested
>   * entropy count. Otherwise, returns an entropy count of 0.
>   */
> -size_t prov_acquire_entropy_from_cpu(RAND_POOL *pool)
> +size_t ossl_prov_acquire_entropy_from_cpu(RAND_POOL *pool)
>  {
>      size_t bytes_needed;
>      unsigned char *buffer;
> ```

Cool. I'll take care of that too in the PR.

**Comment by rsbeckerca** [comment]
Interesting thing: When I modified `BIO_free` instead of `BIO_free_all` with `BIO_flush` the fix stopped working. I'm going back to the debugging board to figure out why.

**Comment by rsbeckerca** [comment]
Replacing prior comment: When running openssl standalone:
```
apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - > providers/fipsmodule.cnf
```
The operation succeeds with my fix. When `./util/wrap.pl` is added to the mix, `providers/fipsmodule.cnf` is now empty. I'm going digging in there.

**Comment by rsbeckerca** [comment]
@levitte There's definitely an issue with the perl wrapper (or perl on NonStop). It appears that `my $waitcode = system @cmd;` eats stdout on NonStop. Is there an alternative?

**Comment by levitte** [comment]
> It appears that `my $waitcode = system @cmd;` eats stdout on NonStop. Is there an alternative?

First of all, I'd like to suggest that you file a bug report to whoever that should fix the underlying bug.  All opened files (that's stdout, among others) should be flushed before program exit.

However, perl has a mechanism...  I hope.  Try [`$| = 1;`](https://perldoc.perl.org/perlvar#$%7C) somewhere before that line.

**Comment by rsbeckerca** [comment]
> 
> 
> > It appears that `my $waitcode = system @cmd;` eats stdout on NonStop. Is there an alternative?
> 
> First of all, I'd like to suggest that you file a bug report to whoever that should fix the underlying bug. All opened files (that's stdout, among others) should be flushed before program exit.
> 
> However, perl has a mechanism... I hope. Try [`$| = 1;`](https://perldoc.perl.org/perlvar#$%7C) somewhere before that line.

Yeah, I tried that one. It didn't help. I'm going to report it. Something else...

There is a file named `-i` being created each time I run the command with perl involved. That file contains the correct output that is supposed to go to `providers/fipsmodule.cnf`. Without the perl wrapper, the output goes to the proper place. Go figure.

**Comment by rsbeckerca** [comment]
I created a PR for the BIO change. This does not completely fix this issue, but I think the `util/wrap.pl` is something completely different.

**Comment by levitte** [comment]
Hmmmmm

Please add this in util/wrap.pl, somewhere before `my $waitcode = system @cmd;`:

``` perl
print STDERR "DEBUG: \@cmd = ", join(' ', @cmd), "\n";
```

If you try something simple like `./util/wrap.pl apps/openssl version > version.txt`, you should get something like this:

```
DEBUG: @cmd = ./util/shlib_wrap.sh apps/openssl version
```

I have no idea where `-i` comes from...

**Comment by rsbeckerca** [comment]
> 
> 
> Hmmmmm
> 
> Please add this in util/wrap.pl, somewhere before `my $waitcode = system @cmd;`:
> 
> ```perl
> print STDERR "DEBUG: \@cmd = ", join(' ', @cmd), "\n";
> ```
> 
> If you try something simple like `./util/wrap.pl apps/openssl version > version.txt`, you should get something like this:
> 
> ```
> DEBUG: @cmd = ./util/shlib_wrap.sh apps/openssl version
> ```
> 
> I have no idea where `-i` comes from...

Nor do I, it does not happen if I run perl in debug mode. However, here's the output:
```
DEBUG: @cmd = util/../util/shlib_wrap.sh apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out -i
```
So there's the `-i`, which looks like it might be coming from an unterminated buffer.

**Comment by rsbeckerca** [comment]
It's not a buffer overrun, which was my working hypothesis:
```
$ util/wrap.pl apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out - -section_name fips_sect >providers/fipsmodule.cnf
DEBUG: @cmd = util/../util/shlib_wrap.sh apps/openssl fipsinstall -module providers/fips.so -provider_name fips -mac_name HMAC -section_name fips_sect -out -i -section_name fips_sect
```
The `-` is being definitely being converted to a `-i` for some weird reason.

**Comment by rsbeckerca** [comment]
@levitte Is it possible to change the first line of the wrap.pl from `#!/usr/bin/env perl` to `#!/usr/bin/perl`? The `env` program specifically changes `-` to `-i`. From the linux man page:

> A mere - implies -i.

This appears to be the root cause and is outside perl. Alternatively, if the wrapper is run explicitly, using `perl util/wrap.pk`, the argument is passed correctly, so `env` and `-` is the cause of this problem.

**Comment by rsbeckerca** [comment]
Created PR #14613 to deal with the argument translation.

**Comment by paulidale** [comment]
env is supposed to stop processing it's arguments when it finds the command name it's going to execute.  I'd call this a bug in your env.  It might be possible to fix this on our side, but pointing to perl isn't the way to do it.

What was wrong with `-out providers/fipsmodule.cnf`?

**Comment by rsbeckerca** [comment]
> 
> 
> env is supposed to stop processing it's arguments when it finds the command name it's going to execute. I'd call this a bug in your env. It might be possible to fix this on our side, but pointing to perl isn't the way to do it.
> 
> What was wrong with `-out providers/fipsmodule.cnf`?

It was `-out - providers/fipsmodule.cnf`. The `-` has special meaning to `env` regardless of the operating system. The **bug** on NonStop is being reported but it will take a long time to get fixed and no guarantee of that. However, `-out` construct really should not have been done that way with `env` in the picture.

**Comment by rsbeckerca** [comment]
> 
> 
> > env is supposed to stop processing it's arguments when it finds the command name it's going to execute. I'd call this a bug in your env. It might be possible to fix this on our side, but pointing to perl isn't the way to do it.
> > What was wrong with `-out providers/fipsmodule.cnf`?
> 
> It was `-out - providers/fipsmodule.cnf`. The `-` has special meaning to `env` regardless of the operating system. The **bug** on NonStop is being reported but it will take a long time to get fixed and no guarantee of that.

@paulidale   That begs the question, why couldn't we just use `-out providers/fipsmodule.cnf` in the first place? That's actually a much easier change that doesn't have me messing about in `unix-Makefile.tmpl`.

**Comment by levitte** [comment]
> @paulidale   That begs the question, why couldn't we just use `-out providers/fipsmodule.cnf` in the first place? That's actually a much easier change that doesn't have me messing about in `unix-Makefile.tmpl`.

a `GENERATE[foo]=some-program with args` in build.info will generate this in Makefile:

```
foo: {deps}
        ./util/wrap.pl some-program with args > foo
```

This is, very simply put, because redirection of stdout is the simplest way to get the output into the intended output file.  Otherwise, one will have to make a lot of assumptions about the command being used as generator; it's not at all certain that it will happily use the last command line argument as output file.

**Comment by levitte** [comment]
The fact that `env` massaged the wrong arguments was quite a surprise.

**Comment by rsbeckerca** [comment]
> The fact that `env` massaged the wrong arguments was quite a surprise.

Tell me about it. Currently testing what I think is the least intrusive change.

**Comment by levitte** [comment]
BTW, it's quite possible that this diff fixes things:

``` diff
diff --git a/providers/build.info b/providers/build.info
index 1fab34c28d..4296aa05a6 100644
--- a/providers/build.info
+++ b/providers/build.info
@@ -150,7 +150,7 @@ IF[{- !$disabled{fips} -}]
   DEPEND[|tests|]=fipsmodule.cnf
   GENERATE[fipsmodule.cnf]=../apps/openssl fipsinstall \
         -module providers/$(FIPSMODULENAME) -provider_name fips \
-        -mac_name HMAC -section_name fips_sect -out -
+        -mac_name HMAC -section_name fips_sect
   DEPEND[fipsmodule.cnf]=$FIPSGOAL
 ENDIF
 
```

**Comment by levitte** [comment]
> Tell me about it

I suddenly don't feel quite as adventurous with OpenVMS :wink:

**Comment by rsbeckerca** [comment]
> > Tell me about it
> 
> I suddenly don't feel quite as adventurous with OpenVMS :wink:

Makes me wonder how s390x is doing.

**Comment by rsbeckerca** [comment]
> BTW, it's quite possible that this diff fixes things:
> 
> ``` diff
> diff --git a/providers/build.info b/providers/build.info
> index 1fab34c28d..4296aa05a6 100644
> --- a/providers/build.info
> +++ b/providers/build.info
> @@ -150,7 +150,7 @@ IF[{- !$disabled{fips} -}]
>    DEPEND[|tests|]=fipsmodule.cnf
>    GENERATE[fipsmodule.cnf]=../apps/openssl fipsinstall \
>          -module providers/$(FIPSMODULENAME) -provider_name fips \
> -        -mac_name HMAC -section_name fips_sect -out -
> +        -mac_name HMAC -section_name fips_sect
>    DEPEND[fipsmodule.cnf]=$FIPSGOAL
>  ENDIF
>  
> ```

Very likely. If it does, we won't need my PR.

**Comment by levitte** [comment]
> Makes me wonder how s390x is doing.

Actually quite well

**Comment by rsbeckerca** [comment]
This is resolved.

**Comment by rsbeckerca** [comment]
When building with commit 814581bb7a, the Makefile does not correctly specify the creation of `providers/fipsmodule.cnf` The build line is:
```
$(BLDDIR)/util/wrap.pl apps/openssl fipsinstall -module providers/$(FIPSMODULENAME) -provider_name fips -mac_name HMAC -section_name fips_sect > $@
```
which looks like the prior behaviour of `-out providers/fipsmodule.cnf` has been undone. As a result, FIPS is now broken again on NonStop. This is leaving an empty file in `providers/fipsmodule.cnf`. This also reverted a previously merged changed that would include `$(PERL)` prior to the command.

**Comment by t8m** [comment]
The #14613 was not yet merged.

**Comment by t8m** [comment]
@rsbeckerca could you please amend the #14613 according to the suggestion there? And I'll approve it.

**Comment by rsbeckerca** [comment]
> 
> 
> @rsbeckerca could you please amend the #14613 according to the suggestion there? And I'll approve it.

Done. I hope this fixes it, because the actual line for building `providers/fipsmodule.cnf` has changed. This may have exposed another problem.

**Comment by rsbeckerca** [comment]
I'm running through a full test suite of the expected major builds (std 64-bit, POSIX Threads, Standard Threads-32bit) for OpenSSL 3.0.0 today. will report results here (or elsewhere upon request).
