### ISSUE TITLE
after ./config，CC error 

### ISSUE THREAD

**Issue by githkk** [openssl/openssl#1607]
If i write ./config in external makefile. The CC will be wrong after conifg.  But if i use command ./config in openssl1.1.0 directory, the CC will be right. Why is it different？Thanks

$ make  
Loading for board "g240wb" on platform "brcm"
cd openssl-1.1.0 && ./config no-asm shared --cross-compile-prefix=/opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc- 
Configuring for linux-elf
CC            =/opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc-/usr/local/bin/ccache /opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc-gcc -Wa,-mno-pdr

$ ./config no-asm shared --cross-compile-prefix=/opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc-
CC            =/opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc-gcc

**Comment by levitte** [comment]
`./config` will use the environment variable `CC` if it has a value, and will combine that value with the `--cross-compile-prefix` value, so what I suspect is that the other Makefile defines that environment variable somehow.

The simple solution is to do this in that other Makefile:

```
cd openssl-1.1.0 && CC='' ./config no-asm shared --cross-compile-prefix=/opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc-
```

Have a look at OpenSSL's `INSTALL`, it describes the environment variables the configuration scripts use, there might be others that you might want to clear in a similar fashion.

**Comment by githkk** [comment]
very thanks for your reply. It is strange that does not take effect also, CC is strcat $CC and $(CROSS_COMPILE),may be i need further check.

I found another LD_LIBRARY_PATH=.: /opt/toolchains/crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21/usr/bin//mips-unknown-linux-uclibc-gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -DL_ENDIAN -fomit-frame-pointer -Wl,-rpath,/usr/local/lib -o apps/openssl apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o -L. -lssl -L. -lcrypto -ldl
./libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
./libcrypto.so: undefined reference to `getcontext'
./libcrypto.so: undefined reference to `setcontext'
./libcrypto.so: undefined reference to `makecontext'

link error, I have found some raise it, but still problem here. Thanks

**Comment by levitte** [comment]
Add `no-async` to the `config` arguments.

**Comment by dot-asm** [comment]
It's almost never appropriate to use cross-compiler with ./config, because ./config would normally detect *host* system, and not one that you are actually cross-compiling for. In such situation one should use ./Configure and pass target platform name explicitly. For example in this case I appears that linux-mips would be more appropriate. [But you'd still have to pass no-async as @levitte suggested, as uclibc doesn't provide needed interfaces.]

**Comment by githkk** [comment]
After add no-async, it compile OK. It compile OK with glibc but not uclibc. Uclibc has no support for the interfaces. But if we add no-async, does it impact  openssl features? I see the install said "Do not build support for async operations",  If no big impact and necessary,i won't add a patch to uclibc. Thanks for all of you.

**Comment by levitte** [comment]
Sync operations requires APIs that are obviously not provided, so you won't have async operations either way.  The impact of `no-async` is that you get a proper OpenSSL build ;-)

So it seems this issue is now resolved, can we close this ticket?

**Comment by githkk** [comment]
OK. Tks very much.

**Comment by BrainSlayer** [comment]
just a additional comment. the advise to remove a feature because its implements using a deprecated posix api is unbelievable. the async feature must be fixed using pthreads.  the code must be fixed. its implemented in a wrong way.

**Comment by 0neday** [comment]
update pthreads to fix it

**Comment by apivovarov** [comment]
Looks like it was fixed in 1.1.1a https://github.com/openssl/openssl/pull/7420

**Comment by apivovarov** [comment]
Note: on older OSes, like CentOS 5, BSD 5, and Windows XP or Vista, you will need to configure with no-async when building OpenSSL 1.1.0 and above. The configuration system does not detect lack of the Posix feature on the platforms.
https://wiki.openssl.org/index.php/Compilation_and_Installation

**Comment by BrainSlayer** [comment]
> Looks like it was fixed in 1.1.1a #7420

this is still not a fix. it just avoids compile errors. its still implemented with a wrong deprecated api and ignores the fact that its possible to implement it in a correct way which works on all posix compliant libc implementations

**Comment by levitte** [comment]
The idea behind the async effort was exactly that it was desirable to avoid threads, as they were seen as too costly in certain environments.  I don't remember more details, it's been too many years since I was involved in this stuff.

If someone is interested in making async happen with pthreads, it would be better to *raise a new issue* instead of small comments in a closed issue.  A PR actually doing it would be welcome too!

**Comment by BrainSlayer** [comment]
@levitte would be a major rewrite. but i found something just by doing some research https://github.com/kaniini/libucontext. this should work with no changes requires, except for extra linking of that library
