### ISSUE TITLE
Problems replacing deprecated ECDSA_do_verify by new EVP_PKEY_verify function

### ISSUE THREAD

**Issue by jofaber** [openssl/openssl#18909]
I am working on migrating functions that are deprecated in Ossl-3.0 and replacing them with functions from the new API, mostly EVP_... abstractions. In our legacy code we have a `verify_id` function 
```
bool RAS2::verify_id(::EC_KEY* publicKey, const std::string &strAuthKey, const std::string &strSystemID)
{
  // tCollBinData = std::vector<std::uint8_t>
  tCollBinData collAuthKey;
  if(!mk_AuthKey_data(collAuthKey, strAuthKey))
    return false;

  tCollBinData collSystemID;
  if(!mk_SystemID_data(collSystemID, strSystemID))
    return false;  

  auto pSignature = make_signat(collAuthKey);

  return 1 == ECDSA_do_verify(&collSystemID[SIGN_OFFSET], SIGN_LENGTH, pSignature.get(), publicKey); //deprecated
}
```
`ECDSA_do_verify` succeeds on all unit tests but it is **deprecated**. I replaced verify_id and `ECDSA_do_verify` by this code (where `mk_unique_OSSL_TYPE`-functions hide (de)allocation and return `std::unique_ptrs`):
```
bool RAS2::verify_id(EVP_PKEY* publicKey, const std::string &strAuthKey, const std::string &strSystemID)
{
  tCollBinData collAuthKey;
  if(!mk_AuthKey_data(collAuthKey, strAuthKey))
    return false;

  tCollBinData collSystemID;
  if(!mk_SystemID_data(collSystemID, strSystemID))
    return false;
  // ==> At this point collAuthKey and strSystemID are identical with the old EC api based implementation

  auto ctx = mk_unique_EVP_PKEY_CTX(publicKey);

  const unsigned authkey_len = MAX_LENGTH_SIGNATURE_PART1 + MAX_LENGTH_SIGNATURE_PART2;
  if(!ctx)
    return false;
  else if(EVP_PKEY_verify_init(ctx.get()) <= 0)
    return false;
  else if(0 == EVP_PKEY_is_a(publicKey, "EC"))
    return false;                
  else if(1 == EVP_PKEY_verify(ctx.get(), &collSystemID[SIGN_OFFSET], SIGN_LENGTH, &collAuthKey[0], authkey_len))
    return true;

  return false;
}
```
The `publicKey` argument is successfully read in `PEM` format from a `BIO`. This works with old EC_ api and with the new EVP_ api:
```
unique_Ossl_ptr<EC_KEY> ec_public_key(char pem[]) // old implementation
{
  BIO* bio     = BIO_new_mem_buf(pem, -1);
  EC_KEY* pkey = ::PEM_read_bio_EC_PUBKEY(bio, NULL, NULL, NULL); //deprecated
  BIO_free(bio);
  return mk_unique_EC_KEY(pkey);
}


unique_Ossl_ptr<EVP_PKEY> evp_public_ec_key(char pem[]) // new implementation
{
  BIO* bio     = BIO_new_mem_buf(pem, -1);

  OSSL_DECODER_CTX *dctx;
  EVP_PKEY* evp_pkey = NULL;
  const char *format = "PEM";   // NULL for any format 
  const char *structure = NULL; // any structure 
  const char *keytype = "EC";   // Key type is EC (Elliptical Curve Digital Signature Algo)
  const unsigned key_mgmt = OSSL_KEYMGMT_SELECT_PUBLIC_KEY; //to get a public KEY

  dctx = OSSL_DECODER_CTX_new_for_pkey(&evp_pkey, format, structure, keytype, key_mgmt, NULL, NULL);
  
  bool success = true;
  if(dctx == NULL)
    success = false; //error: no suitable potential decoders found
  else if(OSSL_DECODER_from_bio(dctx, bio))
    success |= EVP_PKEY_is_a(evp_pkey, "EC"); // Must be EC
  else 
    success = false;
  
  OSSL_DECODER_CTX_free(dctx);
  BIO_free(bio);
  
  return success ? mk_unique_EVP_PKEY(evp_pkey) : nullptr_EVP_PKEY();
}
```
So for some given `pemECKeyString`
```
verify_id(     ec_public_key(pemECKeyString).get(), strAuthKey, strSystemID ); //old impl succeeds
verify_id( evp_public_ec_key(pemECKeyString).get(), strAuthKey, strSystemID ); //new impl fails
```
In the new implementation of `verify_id`, context creation, verify_init and check for the "EC" property succeeds. But the `EVP_PKEY_verify` call always fails.
```
  if(!ctx)
    return false;
  else if(EVP_PKEY_verify_init(ctx.get()) <= 0)
    return false;
  else if(0 == EVP_PKEY_is_a(publicKey, "EC"))
    return false;                
  else if(1 == EVP_PKEY_verify(ctx.get(), &collSystemID[SIGN_OFFSET], SIGN_LENGTH, &collAuthKey[0], authkey_len))
    return true;
```

Any hints and help would be appreciated.

--
I am using OpenSSL-3.0.3 on a Mac M1 macOS 12.2.1 (Monterey) Apple clang version 13.0.0.
Same behavior happens on an older MacPro 10.15.6 (Catalina) Apple clang version 12.0.0.

We have an own build of OpenSSL-3.0.3 but perl configdata.pm --dump fails. I only see a perl configdata.pm.in in the repository.

**Comment by t8m** [comment]
The key_mgmt variable should be probably called selection or something like that. Could you try replacing the `OSSL_KEYMGMT_SELECT_PUBLIC_KEY` with `OSSL_KEYMGMT_SELECT_PUBLIC_KEY | OSSL_KEYMGMT_SELECT_ALL_PARAMETERS`?

**Comment by mattcaswell** [comment]
In addition to what @t8m said, the call to `EVP_PKEY_verify` ultimately ends up in some OpenSSL internal code that looks like this:

````
int ossl_ecdsa_verify(int type, const unsigned char *dgst, int dgst_len,
                      const unsigned char *sigbuf, int sig_len, EC_KEY *eckey)
{
    ECDSA_SIG *s;
    const unsigned char *p = sigbuf;
    unsigned char *der = NULL;
    int derlen = -1;
    int ret = -1;

    s = ECDSA_SIG_new();
    if (s == NULL)
        return ret;
    if (d2i_ECDSA_SIG(&s, &p, sig_len) == NULL)
        goto err;
    /* Ensure signature uses DER and doesn't have trailing garbage */
    derlen = i2d_ECDSA_SIG(s, &der);
    if (derlen != sig_len || memcmp(sigbuf, der, derlen) != 0)
        goto err;
    ret = ECDSA_do_verify(dgst, dgst_len, s, eckey);
 err:
    OPENSSL_free(der);
    ECDSA_SIG_free(s);
    return ret;
}
````
So it eventually calls `ECDSA_do_verify` anyway. Before it gets there though it does some checks on the the supplied signature data, i.e. to check that it can be parsed by `d2i_ECDSA_SIG` and that the round trip of going back to to DER via `i2d_ECDSA_SIG` ends up with the same signature data that you started with. You might want to do those checks yourself to confirm that those tests are going to pass.

**Comment by jofaber** [comment]
Thanks @t8m and @mattcaswell for the input!
When I run the `ossl_ecdsa_verify` checks with my test data I am failing here:
```
    if (d2i_ECDSA_SIG(&s, &p, sig_len) == NULL)
        goto err;
```
I suspect it is 'cause my signature data is in PEM format.
Is there an internal function supporting PEM, that is reachable form `EVP_PKEY_verify`?

**Comment by mattcaswell** [comment]
No, the signature is expected to be a DER encoded `ECDSA_SIG` structure. How did your `make_signat` function work in your original code? That appears to spit out an `ECDSA_SIG` structure that can be converted to DER using `i2d_ECDSA_SIG()`.

**Comment by jofaber** [comment]
This is the `make_signat` function of the original code:
```
    unique_Ossl_ptr<ECDSA_SIG> RAS2::make_signat(const tCollBinData& collAuthKey)
    {
      auto pSignature  = mk_unique_ECDSA_SIG();
      auto sig_nullptr = nullptr_ECDSA_SIG();

      if(!pSignature)
        return sig_nullptr;

      unsigned uLengthPart1 = MAX_LENGTH_SIGNATURE_PART1;
      unsigned uLengthPart2 = MAX_LENGTH_SIGNATURE_PART2;

      std::unique_ptr<BIGNUM, void (*)(BIGNUM*)> r(BN_new(), BN_free);
      std::unique_ptr<BIGNUM, void (*)(BIGNUM*)> s(BN_new(), BN_free);

      if(!::BN_bin2bn(&collAuthKey[0], uLengthPart1, r.get()))
        return sig_nullptr;

      if(!::BN_bin2bn(&collAuthKey[uLengthPart1], uLengthPart2, s.get()))
        return sig_nullptr;

      ECDSA_SIG_set0(pSignature.get(), r.release(), s.release());

      return pSignature;
    }
```
I will try to do the conversion.

**Comment by jofaber** [comment]
I did the conversion from ECDSA_SIG to a DER-encoded one using `i2d_ECDSA_SIG`, but the subsequent call of `d2i_ECDSA_SIG` to convert back still returns `NULL`.

In my `verify_id` function I added test code for conversion and inverse conversion:
```
bool RAS2::verify_id(EVP_PKEY* publicKey, const std::string &strAuthKey, const std::string &strSystemID)
{
      . . .

      //=======================================================================
      // Convert ECDSA_SIG sign to DER-encoding
      auto sign = make_signat(collAuthKey);
      unsigned char* der_sig;
      // Query the length of der-encoded signature by passing NULL to the result buffer argument 
      int der_sig_len = i2d_ECDSA_SIG(sign.get(), NULL); 
      // Allocate memory for der_sig
      der_sig = static_cast<unsigned char*>(malloc(der_sig_len));
      // create the DER encoding of ECDSA signature 'sign'
      int der_sig_len2 = i2d_ECDSA_SIG(sign.get(), &der_sig);

      if(der_sig_len != der_sig_len2)
        return false;

      //=======================================================================
      // Simulate argument passing to ossl_ecdsa_verify
      ECDSA_SIG *s;
      const unsigned char *p = der_sig;
      unsigned sig_len = der_sig_len; 

      //=======================================================================
      // Inverse conversion of DER-encoded signature 'p' to ECDSA_SIG 's`
      s = ECDSA_SIG_new();
      if (s == NULL)
        return false;
      else
      { // Convert the DER-encoded signature back to ECDSA_SIG s:
        ECDSA_SIG* ret_sig   = d2i_ECDSA_SIG(&s, &p, sig_len); //ret_sig is NULL but should be 's'
        const BIGNUM* s_r    = ECDSA_SIG_get0_r(s);
        const BIGNUM* sign_r = ECDSA_SIG_get0_r(sign.get());
        int cmp_r = BN_cmp(s_r, sign_r); //cmp_r == -1 (less) but should be 0 (equality)
      }
      //=======================================================================

      . . .
}
```
So I still can not do the conversion properly. Am I missing something?

**Comment by mattcaswell** [comment]
Do the contents of the `der_sig` buffer look sane? What do you get if you dump the contents of that buffer, e.g.

````
    BIO_dump_fp(stdout, der_sig, der_sig_len);
````

**Comment by jofaber** [comment]
ECDSA_SIG buffer dumps are not my favorite good night stories. So I can't tell how to judge sanity. At least it has the correct number of 35 bytes that are also reported by the `der_sig_len` variable.

```
0000 - 00 00 00 00 00 67 3a 3a-5f 29 29 00 00 c1 d4 3b   .....g::_))....;
0010 - eb 01 00 00 01 8c 07 00-00 01 00 00 00 1a 66 69   ..............fi
0020 - 6c 65 3a                                          le:
```

**Comment by mattcaswell** [comment]
That isn't a sane ECDSA_SIG structure.

I think I just spotted the problem. A common gotcha. From the man page for `i2d_ECDSA_SIG`:

> i2d_TYPE() encodes the structure pointed to by a into DER format. If ppout is not NULL, it writes the DER encoded data to the buffer at *ppout, and increments it to point after the data just written. 

The important bit is at the end: "...and increments it to point after the data just written."

So, after the after the `i2d_ECDA_SIG` call the value of `der_sig` no longer points to the start of the buffer where the DER encoding of the ECDSA_SIG structure is - instead it points to the *end* of the encoding of that structure. This is so that you can chain a number of encodings together, and they get written one after the other in the buffer.

**Comment by jofaber** [comment]
Thank you a lot @mattcaswell. This was it  :)

**Comment by mattcaswell** [comment]
No problem.

Is this issue solved now? Can we close it?

**Comment by jofaber** [comment]
let's keep it open for a bit. I'm working on the original issue today which is not completely resolved.

**Comment by jofaber** [comment]
Hi @mattcaswell and open ssl devs, 
in the above comment I summarised my efforts trying to migrate a functional but deprecated validation via `ECDSA_do_verify` to the now recommended `EVP_PKEY_verify`. I hope you have some additional ideas on how to fix the remaining failure.

**Comment by romen** [comment]
> `ret = EVP_PKEY_verify(ctx.get(), &collSystemID[SIGN_OFFSET], SIGN_LENGTH, der_sig, der_sig_len);`

Isn't the order of arguments swapped here? https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_verify.html

First the signature, then the signed data.

**Comment by romen** [comment]
As an aside note, when any of the operations fail, you could also use [`ERR_print_errors_fp()` or similar](https://www.openssl.org/docs/man3.0/man3/ERR_print_errors_fp.html) to get some explanation.

I suspect in this case, given you were seeing a `ret` of `-1`, there might have been some error on the stack saying that the length of the signature was invalid, or something similar.

**Comment by jofaber** [comment]
Hey @romen nice catch :) 
The issue is now solved and thank you for the additional hints!
