### ISSUE TITLE
OSSL_STORE_expect causes OSSL_STORE_load to throw an error

### ISSUE THREAD

**Issue by YushengYangRTI** [openssl/openssl#20472]
I found this problem in OpenSSL 3.0.8.

If I have a file with a certificate concatenated with a private key:

```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

and I have this code:

```
OSSL_STORE_expect(ctx, OSSL_STORE_INFO_CERT);
OSSL_STORE_load(ctx);
OSSL_STORE_load(ctx);
```

the second `OSSL_STORE_load` will result in `OSSL_STORE_error(ctx) == 1`.
This was not the behavior in OpenSSL 1.1.1t, and it seems to contradict the [documentation](https://www.openssl.org/docs/man3.0/man3/OSSL_STORE_expect.html):

```
OSSL_STORE_expect() helps applications filter what OSSL_STORE_load() returns by specifying a OSSL_STORE_INFO type.
```

In OpenSSL 1.1.1t, expect() was acting like a filter, and it was causing load() to skip over unexpected artifacts. In OpenSSL 3.0.8, expect() is acting more like a way to set up an assertion that must not fail.

**Comment by levitte** [comment]
It would have been nice to see the error produced.  Would you mind adding this line?

``` C
ERR_print_errors_fp(stderr);
```

**Comment by YushengYangRTI** [comment]
```
005D040400000000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
```

**Comment by tomhughes** [comment]
The same thing has started happening in the 3.1 line between the 3.1.0 and 3.1.3 releases.

**Comment by tomhughes** [comment]
I think it's actually at end of file that `OSSL_STORE_error` returns true (as well as `OSSL_STORE_eof`) but only if there is a filter installed with `OSSL_STORE_expect`.

**Comment by levitte** [comment]
We recently made a change in the logic for how error and eof was treated, see 17dd9a2c6262c00800301fddd9441a9c590a630e.  I think the behavior observed here may be due to the error flag never being cleared before the next load.

The fix is present in the latest releases (3.0.11 and 3.1.3), please try them out to see if they helped.

**Comment by tomhughes** [comment]
It was actually when I upgraded from 3.1.0 to 3.1.3 today that I ran in to this so no I don't think 3.1.3 helps ;-)

I had a file with three certificates (and nothing else) and read it with a filter on certificates installed and the first three times I called `OSSL_STORE_load` there was a non-null result with details of the certificate and the fourth time it returned null and both `OSSL_STORE_eof` and `OSSL_STORE_error` were returning true.

**Comment by t8m** [comment]
Could it be that it is actually regression from https://github.com/openssl/openssl/commit/17dd9a2c6262c00800301fddd9441a9c590a630e ? It is suspicious.

**Comment by tomhughes** [comment]
I can confirm that reverting 17dd9a2c6262c00800301fddd9441a9c590a630e appears to restore the old behaviour,

**Comment by t8m** [comment]
@tomhughes would it be possible to submit here an example of the code and data which trigger this regression?

**Comment by tomhughes** [comment]
Sure, here's a test case:

```c
#include <stdio.h>

#include "openssl/err.h"
#include "openssl/store.h"
#include "openssl/x509.h"

int main( int argc, char **argv )
{
   OSSL_STORE_CTX *ctx = OSSL_STORE_open( "ossl.pem", NULL, "", NULL, NULL );

   while ( !OSSL_STORE_eof( ctx ) )
   {
      OSSL_STORE_INFO *info = OSSL_STORE_load( ctx );

      if ( info && OSSL_STORE_INFO_get_type( info ) == OSSL_STORE_INFO_CERT )
      {
         X509 *cert = OSSL_STORE_INFO_get1_CERT( info );
         X509_NAME *name = X509_get_subject_name( cert );
         char buffer[256];

         printf( "CERT: %s\n", X509_NAME_oneline( name, buffer, sizeof( buffer ) ) );
      }
      else if ( info == NULL && OSSL_STORE_error( ctx ) )
      {
         printf( "ERROR: %lu\n", ERR_get_error() );
      }
   }

   OSSL_STORE_close( ctx );

   return 0;

}
```

you can run it against any file, but here's an example:

```
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----
```

Note that it seems I was wrong about needing to have a filter installed.

Building against 3.1.3 will give output like:

```
CERT: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
ERROR: 0
```

while earlier versions will not have the `ERROR` line.

I've also debugged it down through openssl now and located the problem, which appears to be https://github.com/openssl/openssl/blob/30224a248495ad604a06b8977fa3aa1cc75b9d0d/crypto/encode_decode/decoder_lib.c#L100which logs a "No data to decode" error but also returns false.

The layer above at https://github.com/openssl/openssl/blob/30224a248495ad604a06b8977fa3aa1cc75b9d0d/providers/implementations/storemgmt/file_store.c#L533 then carefully ignores that error and clears the error stack but leaves the return value alone, causing the already identified code to set the error flag now that it no longer does an EOF check.

**Comment by Et7f3** [comment]
@tomhughes
Can you execute [`perl -pi -e 'chomp if eof' ossl.pem`](https://unix.stackexchange.com/a/541415/246754) and rerun your code. I don't see `ERROR: 0` after.

This might be symptom of:
read one cert
their is some bytes in buffer (mostly white space like \r or \n)
read another cert (it can only consume white chars) but their is none so it fail.

I see two solution:
- OSSL_STORE_load: read one cert and white space
- OSSL_STORE_eof: seek for a `-----BEGIN` (I don't know if the number of dash is important)

For second solution I don't propose to eat white space because I have seen this kind of files with text (comment or part of the certificate ?)

```
RqEIr9baRRmW1FMdW4R58MD3R++Lj8UGrp1MYp3/RgT408m2ECVAdf4WqslKYIYv
uu8wd+RU4riEmViAqhOLUTpPSPaLtrMwDDAKBggrBgEFBQcDAQ==
-----END TRUSTED CERTIFICATE-----

AC RAIZ FNMT-RCM SERVIDORES SEGUROS
-----BEGIN CERTIFICATE-----
MIICbjCCAfOgAwIBAgIQYvYybOXE42hcG2LdnC6dlTAKBggqhkjOPQQDAzB4MQsw
CQYDVQQGEwJFUzERMA8GA1UECgwIRk5NVC1SQ00xDjAMBgNVBAsMBUNlcmVzMRgw
FgYDVQRhDA9WQVRFUy1RMjgyNjAwNEoxLDAqBgNVBAMMI0FDIFJBSVogRk5NVC1S
Q00gU0VSVklET1JFUyBTRUdVUk9TMB4XDTE4MTIyMDA5MzczM1oXDTQzMTIyMDA5
MzczM1oweDELMAkGA1UEBhMCRVMxETAPBgNVBAoMCEZOTVQtUkNNMQ4wDAYDVQQL
DAVDZXJlczEYMBYGA1UEYQwPVkFURVMtUTI4MjYwMDRKMSwwKgYDVQQDDCNBQyBS
QUlaIEZOTVQtUkNNIFNFUlZJRE9SRVMgU0VHVVJPUzB2MBAGByqGSM49AgEGBSuB
BAAiA2IABPa6V1PIyqvfNkpSIeSX0oNnnvBlUdBeh8dHsVnyV0ebAAKTRBdp20LH
sbI6GA60XYyzZl2hNPk2LEnb80b8s0RpRBNm/dfF/a82Tc4DTQdxz69qBdKiQ1oK
Um8BA06Oi6NCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYD
VR0OBBYEFAG5L++/EYZg8k/QQW6rcx/n0m5JMAoGCCqGSM49BAMDA2kAMGYCMQCu
SuMrQMN0EfKVrRYj3k4MGuZdpSRea0R7/DjiT8ucRRcRTBQnJlU5dUoDzBOQn5IC
MQD6SmxgiHPz7riYYqnOK8LZiqZwMR2vsJRM60/G49HzYqc8/5MuB1xJAWdpEgJy
v+c=
-----END CERTIFICATE-----

Trusted for:
  - 1.3.6.1.5.5.7.3.1 (RFC5280: serverAuth key usage)
-----BEGIN TRUSTED CERTIFICATE-----
MIICbjCCAfOgAwIBAgIQYvYybOXE42hcG2LdnC6dlTAKBggqhkjOPQQDAzB4MQsw
CQYDVQQGEwJFUzERMA8GA1UECgwIRk5NVC1SQ00xDjAMBgNVBAsMBUNlcmVzMRgw
FgYDVQRhDA9WQVRFUy1RMjgyNjAwNEoxLDAqBgNVBAMMI0FDIFJBSVogRk5NVC1S
Q00gU0VSVklET1JFUyBTRUdVUk9TMB4XDTE4MTIyMDA5MzczM1oXDTQzMTIyMDA5
MzczM1oweDELMAkGA1UEBhMCRVMxETAPBgNVBAoMCEZOTVQtUkNNMQ4wDAYDVQQL
DAVDZXJlczEYMBYGA1UEYQwPVkFURVMtUTI4MjYwMDRKMSwwKgYDVQQDDCNBQyBS
QUlaIEZOTVQtUkNNIFNFUlZJRE9SRVMgU0VHVVJPUzB2MBAGByqGSM49AgEGBSuB
BAAiA2IABPa6V1PIyqvfNkpSIeSX0oNnnvBlUdBeh8dHsVnyV0ebAAKTRBdp20LH
sbI6GA60XYyzZl2hNPk2LEnb80b8s0RpRBNm/dfF/a82Tc4DTQdxz69qBdKiQ1oK
Um8BA06Oi6NCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYD
VR0OBBYEFAG5L++/EYZg8k/QQW6rcx/n0m5JMAoGCCqGSM49BAMDA2kAMGYCMQCu
SuMrQMN0EfKVrRYj3k4MGuZdpSRea0R7/DjiT8ucRRcRTBQnJlU5dUoDzBOQn5IC
MQD6SmxgiHPz7riYYqnOK8LZiqZwMR2vsJRM60/G49HzYqc8/5MuB1xJAWdpEgJy
v+cwDDAKBggrBgEFBQcDAQ==
-----END TRUSTED CERTIFICATE-----

```

**Comment by tomhughes** [comment]
I can confirm that fixes it:

```
rawhide [~] % rpm -q openssl
openssl-3.2.1-2.fc40.x86_64
rawhide [~] % md5sum ossl.pem 
505444090df336fa2a75cc94cb3ce079  ossl.pem
rawhide [~] % ./ossl ossl.pem
CERT: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
ERROR: 0
rawhide [~] % perl -pi -e 'chomp if eof' ossl.pem
rawhide [~] % md5sum ossl.pem                    
6b58e47fce41e46ec8af7d68910e7454  ossl.pem
rawhide [~] % ./ossl ossl.pem
CERT: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
```

**Comment by nhorman** [comment]
Is seems this issue has been resolved, marking as inactive to be closed at the end of the 3.4 dev cycle barring further discussion

**Comment by mdounin** [comment]
This issue seems to be incorrectly marked as resolved.

The issue is still here as of current master, and `OSSL_STORE_load()` returns NULL with both `OSSL_STORE_error()` and `OSSL_STORE_eof()` when trying to read a second certificate from a PEM file with just one certificate.

Note well that `perl -pi -e 'chomp if eof' ossl.pem` test as suggested in https://github.com/openssl/openssl/issues/20472#issuecomment-2040029750 removes newline at the end of the file, making it non-text from POSIX point of view. While this can be used to better understand the issue, it is not a fix.

Another relevant issue is https://github.com/openssl/openssl/issues/26412.
