### ISSUE TITLE
memory leaks in x_name.c

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#2109]
Under low memory a memory leak was observed with openssl-1.0.2j:

The error handling in x509_name_ex_d2i is unable to clean up all x509 objects
when an error happens in sk_X509_NAME_ENTRY_push due to OOM.
Also in x509_name_encode and x509_name_canon there is a small memory leak
if sk_STACK_OF_X509_NAME_ENTRY_push fails due to OOM.

```
==11507==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7f5f689e8310 in __interceptor_malloc ../../../../gcc-7-20161211/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x2153dfa in CRYPTO_malloc crypto/mem.c:346
    #2 0x21ac92c in sk_new crypto/stack/stack.c:162
    #3 0x21ac92c in sk_new_null crypto/stack/stack.c:154
    #4 0x220a1f4 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:634
    #5 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #6 0x220bf53 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:206
    #7 0x21f5e00 in x509_name_ex_d2i crypto/asn1/x_name.c:207
    #8 0x220be08 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:244
    #9 0x2208e33 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:696
    #10 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #11 0x220cbd4 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:447
    #12 0x2208e33 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:696
    #13 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #14 0x220e917 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:447
    #15 0x220e917 in ASN1_item_d2i crypto/asn1/tasn_dec.c:146
    #16 0x235d291 in ASN1_item_d2i_bio crypto/asn1/a_d2i_fp.c:119
    #17 0x223c801 in X509_load_cert_file crypto/x509/by_file.c:163
    #18 0x223c801 in by_file_ctrl crypto/x509/by_file.c:118

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f5f689e8310 in __interceptor_malloc ../../../../gcc-7-20161211/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x2153dfa in CRYPTO_malloc crypto/mem.c:346
    #2 0x21ac92c in sk_new crypto/stack/stack.c:162
    #3 0x21ac92c in sk_new_null crypto/stack/stack.c:154
    #4 0x220a1f4 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:634
    #5 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #6 0x22094e9 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:206
    #7 0x22094e9 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:668
    #8 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #9 0x220bf53 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:206
    #10 0x21f5e00 in x509_name_ex_d2i crypto/asn1/x_name.c:207
    #11 0x220be08 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:244
    #12 0x2208e33 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:696
    #13 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #14 0x220cbd4 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:447
    #15 0x2208e33 in asn1_template_noexp_d2i crypto/asn1/tasn_dec.c:696
    #16 0x220ac6c in asn1_template_ex_d2i crypto/asn1/tasn_dec.c:584
    #17 0x220e917 in ASN1_item_ex_d2i crypto/asn1/tasn_dec.c:447
    #18 0x220e917 in ASN1_item_d2i crypto/asn1/tasn_dec.c:146
    #19 0x2102889 in ssl3_get_client_certificate ssl/s3_srvr.c:3243
    #20 0x2107c97 in ssl3_accept ssl/s3_srvr.c:593
    #21 0x212c7de in ssl3_read_bytes ssl/s3_pkt.c:1207
    #22 0x211e625 in ssl3_read_internal ssl/s3_lib.c:4459
    #23 0x211e625 in ssl3_read ssl/s3_lib.c:4483


--- crypto/asn1/x_name.c.orig   2016-09-26 11:49:07.000000000 +0200
+++ crypto/asn1/x_name.c        2016-12-17 11:46:49.537496141 +0100
@@ -178,6 +178,16 @@ static void x509_name_ex_free(ASN1_VALUE
     *pval = NULL;
 }

+static void local_sk_X509_NAME_ENTRY_free(STACK_OF(X509_NAME_ENTRY) *ne)
+{
+    sk_X509_NAME_ENTRY_free(ne);
+}
+
+static void local_sk_X509_NAME_ENTRY_pop_free(STACK_OF(X509_NAME_ENTRY) *ne)
+{
+    sk_X509_NAME_ENTRY_pop_free(ne, X509_NAME_ENTRY_free);
+}
+
 static int x509_name_ex_d2i(ASN1_VALUE **val,
                             const unsigned char **in, long len,
                             const ASN1_ITEM *it, int tag, int aclass,
@@ -228,13 +238,14 @@ static int x509_name_ex_d2i(ASN1_VALUE *
             entry->set = i;
             if (!sk_X509_NAME_ENTRY_push(nm.x->entries, entry))
                 goto err;
+            sk_X509_NAME_ENTRY_set(entries, j, NULL);
         }
-        sk_X509_NAME_ENTRY_free(entries);
     }
-    sk_STACK_OF_X509_NAME_ENTRY_free(intname.s);
     ret = x509_name_canon(nm.x);
     if (!ret)
         goto err;
+    sk_STACK_OF_X509_NAME_ENTRY_pop_free(intname.s,
+                                         local_sk_X509_NAME_ENTRY_free);
     nm.x->modified = 0;
     *val = nm.a;
     *in = p;
@@ -242,6 +253,8 @@ static int x509_name_ex_d2i(ASN1_VALUE *
  err:
     if (nm.x != NULL)
         X509_NAME_free(nm.x);
+    sk_STACK_OF_X509_NAME_ENTRY_pop_free(intname.s,
+                                         local_sk_X509_NAME_ENTRY_pop_free);
     ASN1err(ASN1_F_X509_NAME_EX_D2I, ERR_R_NESTED_ASN1_ERROR);
     return 0;
 }
@@ -267,16 +280,6 @@ static int x509_name_ex_i2d(ASN1_VALUE *
     return ret;
 }

-static void local_sk_X509_NAME_ENTRY_free(STACK_OF(X509_NAME_ENTRY) *ne)
-{
-    sk_X509_NAME_ENTRY_free(ne);
-}
-
-static void local_sk_X509_NAME_ENTRY_pop_free(STACK_OF(X509_NAME_ENTRY) *ne)
-{
-    sk_X509_NAME_ENTRY_pop_free(ne, X509_NAME_ENTRY_free);
-}
-
 static int x509_name_encode(X509_NAME *a)
 {
     union {
@@ -299,12 +302,16 @@ static int x509_name_encode(X509_NAME *a
             entries = sk_X509_NAME_ENTRY_new_null();
             if (!entries)
                 goto memerr;
-            if (!sk_STACK_OF_X509_NAME_ENTRY_push(intname.s, entries))
+            if (!sk_STACK_OF_X509_NAME_ENTRY_push(intname.s, entries)) {
+                sk_X509_NAME_ENTRY_free(entries);
                 goto memerr;
+            }
             set = entry->set;
         }
-        if (!sk_X509_NAME_ENTRY_push(entries, entry))
+        if (!sk_X509_NAME_ENTRY_push(entries, entry)) {
+            X509_NAME_ENTRY_free(entry);
             goto memerr;
+        }
     }
     len = ASN1_item_ex_i2d(&intname.a, NULL,
                            ASN1_ITEM_rptr(X509_NAME_INTERNAL), -1, -1);
@@ -370,8 +377,10 @@ static int x509_name_canon(X509_NAME *a)
             entries = sk_X509_NAME_ENTRY_new_null();
             if (!entries)
                 goto err;
-            if (!sk_STACK_OF_X509_NAME_ENTRY_push(intname, entries))
+            if (!sk_STACK_OF_X509_NAME_ENTRY_push(intname, entries)) {
+                sk_X509_NAME_ENTRY_free(entries);
                 goto err;
+            }
             set = entry->set;
         }
         tmpentry = X509_NAME_ENTRY_new();

```

**Comment by FdaSilvaYY** [comment]
This one was fixed in the trunk recently, after two trials at least...
Have you compare your fix against the current on in the trunk ?
See History of https://github.com/openssl/openssl/commits/master/crypto/x509/x_name.c

**Comment by bernd-edlinger** [comment]
Note that the pull request #2127 contains an updated version of the
above patch that fixes at least two additional memory leaks.
These are not yet fixed on trunk IMHO.

**Comment by bernd-edlinger** [comment]
The version on the trunk is rather tricky, but it will crash if x509_name_ex_new fails to allocate `nm.x`.

**Comment by bernd-edlinger** [comment]
OK, this was fixed on all active branches.
