### ISSUE TITLE
CMP connect timeout with 3.2.0 or fails on `localhost`

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22870]
I'm getting:
```
# cmp_main:../apps/cmp.c:3077:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:../apps/cmp.c:2438:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:../apps/cmp.c:2088:CMP info: will contact http://localhost:36257/pkix/
# CMP info: sending IR
# CMP error: connect timeout
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../build_static/util/wrap.pl ../../../../build_static/apps/openssl cmp -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../build_static/test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 -server 'localhost:36257' => 1
    not ok 2 - server domain name

    #   Failed test 'server domain name'
    #   at ../test/recipes/80-test_cmp_http.t line 151.
    #          got: '0'
    #     expected: '1'
```

Full log at: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=arm64&ver=3.2.0-1&stamp=1701011796&raw=0

I've scheduled an other build (on arm64) to see if this is a reproducible.

**Comment by kroeckx** [comment]
So a new build was successful: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=arm64&ver=3.2.0-1&stamp=1701286006&raw=0

**Comment by mattcaswell** [comment]
@kroeckx - can this be closed?

**Comment by kroeckx** [comment]
No, the issue remains, we've seen this in various other logs, see for instance: https://buildd.debian.org/status/logs.php?pkg=openssl&ver=3.2.1-1&arch=amd64

**Comment by t8m** [comment]
@DDvO any idea why this could be happening?

**Comment by DDvO** [comment]
I had not noticed this issue before; good that you pointed me to it.

What I see from the provided log and also from general experience,
for the vast majority of test cases there are no connection (timeout) issues,
but under certain circumstances looks like the client did not get a response in time,
at least for the `connection` aspect of the tests.

This must be somehow due to the underlying system, 
likely related to too much general load.

To be more on the safe side here, 
I suggest slightly increasing in `test/recipes/80-test_cmp_http_data/Mock/test.cnf` the value in line 124:
```
msg_timeout = 5
```

**Comment by t8m** [comment]
> I suggest slightly increasing in `test/recipes/80-test_cmp_http_data/Mock/test.cnf` the value in line 124:
> 
> ```
> msg_timeout = 5
> ```

Will you submit a PR, please?

**Comment by t8m** [comment]
I've seen such failure in our CI as well although very rarely.

**Comment by DDvO** [comment]
> > I suggest slightly increasing in `test/recipes/80-test_cmp_http_data/Mock/test.cnf` the value in line 124:
> > ```
> > msg_timeout = 5
> > ```
> 
> Will you submit a PR, please?

Done.

**Comment by kroeckx** [comment]
It still fails: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=ppc64el&ver=3.2.1-2&stamp=1708642484&raw=0

**Comment by DDvO** [comment]
This failure is not due to connection timeout, but pretty surely because on the host running the tests the special 'domain' name `localhost` does not resolve to `127.0.0.1`:
```
# CMP info: sending IR
# CMP error: Connection refused:calling connect()
# CMP error: connect error
# CMP error: Connection refused:calling connect(localhost, 45033)
# CMP error: connect error
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../build_static/util/wrap.pl ../../../../build_static/apps/openssl cmp -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../build_static/test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 -server 'localhost:45033' => 1
    not ok 2 - server domain name
 ```

**Comment by DDvO** [comment]
I wonder how other (SSL/TLS/QUIC) tests, which partly also use the special name `localhost`, cope with this.

**Comment by kroeckx** [comment]
/etc/hosts contains:
```
127.0.0.1	localhost
2a02:16a8:dc41:100::244	ppc64el-conova-02.debian.org	ppc64el-conova-02

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

The hosts that works has:
```
127.0.0.1	localhost
140.211.166.196	ppc64el-osuosl-01.debian.org	ppc64el-osuosl-01

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Note that ppc64el-conova-02.debian.org does not have a public IPv4 address.

**Comment by kroeckx** [comment]
The not having a public IPv4 address seems to be common on all the hosts it fails on. 127.0.0.1 is the only IPv4 address they have.

**Comment by DDvO** [comment]
Strange - so according to `/etc/hosts`, the two machines have identical configuration w.r.t `localhost`.
Whether or not they (in addition) have a public IPv4 address should not make a difference here.

I suspect that some other part of the local DNS resolution goes wrong on `localhost`.
Is there a difference in the behavior on `ping localhost`?

Maybe the IPv6 configuration interferes on the host where that test case goes wrong -
does it help if you remove the line 
`::1     localhost ip6-localhost ip6-loopback` 
from `/etc/hosts`?

**Comment by DDvO** [comment]
Hmm, then I guess there may be some interference with IPv6.
Again, does it help if you remove the line `::1     localhost ip6-localhost ip6-loopback` ?

**Comment by kroeckx** [comment]
I have no idea. If there would be porter boxes that have this problem, then I don't have access to change that.

In any case, if you try to connect to a host you should always have a loop going over all the addresses until you find one that works.

**Comment by DDvO** [comment]
So how if we add to `OSSL_HTTP_open()` a special handling:
In case opening a connection to `localhost` fails, retry with `127.0.0.1`?

**Comment by kroeckx** [comment]
A proper server has 2 options:
- 2 sockets, one for IPv4, and for IPv6. (Or more if there are more addresses it wants to listen to.)
- 1 socket that supports both.


A proper client will see 2 addresses and loop over them until one works or all fail. There is no special case for localhost.

From what I understand, both the client and server are broken.

**Comment by DDvO** [comment]
How capable should our little OpenSSL HTTP client become?
I already made it much more capable than the original very primitive one, 
which was used just for fetching OCSP responses and CRLs.
Certainly we do not wanna emulate cURL and wget.

**Comment by kroeckx** [comment]
So this most likely is related to using AI_ADDRCONFIG. Do we actually try to listen to localhost, or to everything?

Trying all addresses is something anything using sockets should do, not just an http client.

**Comment by kroeckx** [comment]
It seems to be using a combination of 127.0.0.1 and localhost?

**Comment by DDvO** [comment]
Ah, very good point that the strange behavior should be due to `AI_ADDRCONFIG`!

This is used by `BIO_lookup_ex()` while the special behavior is not documented for it,
but here: https://man7.org/linux/man-pages/man3/getaddrinfo.3.html

> If hints.ai_flags includes the AI_ADDRCONFIG flag, then IPv4
 addresses are returned in the list pointed to by res only if the
       local system has at least one IPv4 address configured, and IPv6
       addresses are returned only if the local system has at least one
       IPv6 address configured.  The loopback address is not considered
       for this case as valid as a configured address.  This flag is
       useful on, for example, IPv4-only systems, to ensure that
       getaddrinfo() does not return IPv6 socket addresses that would
       always fail in [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html) or [bind(2)](https://man7.org/linux/man-pages/man2/bind.2.html).

So as ppc64el-conova-02.debian.org does not have a public IPv4 address configured,
the IPv4 address of `localhost` apparently is not used for connecting.

Does it help if you add 
```
    BIO_set_conn_ip_family(cbio, BIO_FAMILY_IPV4);
```
to `http_new_bio()` in `crypto/http/http_client.c`
and
```
    BIO_set_accept_ip_family(acbio, BIO_FAMILY_IPV4); 
```
to `http_server_init()` in `apps/http_server.c`?

**Comment by kroeckx** [comment]
Not having had the time to properly look at things, it seems localhost is used at one place, which will probably get ::1 only, and 127.0.0.1 at the other place.

**Comment by DDvO** [comment]
Ah, right, so this should not work either.
Then I suggest we simply disable the problematic test case involving `localhost`, as it is anyway not really CMP-specific.
