### ISSUE TITLE
Unresolved symbols when built statically for Visual Studio

### ISSUE THREAD

**Issue by beamer159** [openssl/openssl#6635]
If I build OpenSSL for Windows dynamically, it compiles fine in a project:

    perl Configure VC-WIN32 --prefix=C:\OpenSSL-shared --openssldir=C:\OpenSSL-shared
    nmake
    nmake install

However, if I build OpenSSL statically, I get a number of unresolved symbol errors when compiling:

    perl Configure VC-WIN32 --prefix=C:\OpenSSL-static --openssldir=C:\OpenSSL-static no-shared
    nmake
    nmake install

Here is the code am running:

    #include <openssl\evp.h>
    
    int main()
    {
    	OpenSSL_add_all_algorithms();
    	OPENSSL_cleanup();
    	return 0;
    }

And here is the error list:

    Error	LNK2001	unresolved external symbol __imp__WSAGetLastError@0	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(bss_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__recv@16 referenced in function _sock_read	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(bss_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__send@16 referenced in function _sock_write	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(bss_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__WSASetLastError@4 referenced in function _sock_write	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(bss_sock.obj)	1	
    Error	LNK2001	unresolved external symbol __imp__ntohs@4	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_addr.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__getaddrinfo@16 referenced in function _BIO_lookup	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_addr.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__freeaddrinfo@4 referenced in function _BIO_ADDRINFO_free	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_addr.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__getnameinfo@28 referenced in function _addr_strings	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_addr.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__ioctlsocket@12 referenced in function _BIO_socket_ioctl	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__getsockname@12 referenced in function _BIO_sock_info	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__getsockopt@20 referenced in function _BIO_sock_error	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__ntohs@4 referenced in function _BIO_get_port	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__gethostbyname@4 referenced in function _BIO_gethostbyname	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__WSAStartup@8 referenced in function _BIO_sock_init	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__WSACleanup@0 referenced in function _bio_sock_cleanup_int	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__WSAGetLastError@0 referenced in function _BIO_accept	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock.obj)	1	
    Error	LNK2001	unresolved external symbol __imp__getsockopt@20	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2001	unresolved external symbol __imp__WSAGetLastError@0	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__accept@12 referenced in function _BIO_accept_ex	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__bind@12 referenced in function _BIO_listen	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__closesocket@4 referenced in function _BIO_accept_ex	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__connect@12 referenced in function _BIO_connect	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__listen@8 referenced in function _BIO_listen	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__setsockopt@20 referenced in function _BIO_connect	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__socket@12 referenced in function _BIO_socket	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(b_sock2.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertOpenStore@20 referenced in function _capi_open_store	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertCloseStore@8 referenced in function _capi_find_key	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertEnumCertificatesInStore@8 referenced in function _capi_find_cert	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertFindCertificateInStore@24 referenced in function _capi_find_cert	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertDuplicateCertificateContext@4 referenced in function _capi_load_ssl_client_cert	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _capi_dsa_free	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK2019	unresolved external symbol __imp__CertGetCertificateContextProperty@16 referenced in function _capi_cert_get_fname	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\TestCpp\libcrypto.lib(e_capi.obj)	1	
    Error	LNK1120	28 unresolved externals	TestCpp	C:\Users\myusername\Documents\Visual Studio 2015\Projects\TestCpp\Debug\TestCpp.exe	1	

I do not know why it is looking for `libcrypto.lib` in the project folder instead of `C:\OpenSSL-static\lib\` since I added that path to the additional library dependencies, but I went ahead and copied the library file to the project folder anyway, and these errors still occur.

**Comment by mspncp** [comment]
These are all symbols from microsoft system libraries. Did you add the corresponding import libs to your executable's project? Try adding Crypt32.lib and Ws2_32.lib. If there are any unresolved symbols left, google for "MSDN <functionname>".

Hope that helps. Not an OpenSSL issue, closing.

**Comment by dot-asm** [comment]
There is "Linking your application" section in NOTES.WIN.

**Comment by LuanDevecchi** [comment]
```cpp
#pragma comment(lib, "crypt32")
#pragma comment(lib, "ws2_32.lib")
```
fixes your problem.

**Comment by TheNageek** [comment]
@LuanDevecchi looking to implement this fix as well, seems like it's worked for others, but when I include that within a project .h file I get "C1021: invalid preprocessor command". 

Just wondering where you ended up placing that pragma to avoid this?

**Comment by TheNageek** [comment]
Scratch that, solved by placing `crypt32.lib` in same directory as other .lib files

**Comment by bbalaban** [comment]
I'm linking my w64 app with all the libs specified in the Notes-Windows readme (using Visual Studio 2019 community ed).
Still getting around 40 unresolved link errors, such as these 2:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_strspn referenced in function PEM_get_EVP_CIPHER_INFO
Error	LNK2019	unresolved external symbol __imp_tolower referenced in function print_labeled_bignum

This is using a locally build static libssl.lib and libcrypto.lib
I'm also linking with legacy_stdio_definitions.lib
What am I missing?
