### ISSUE TITLE
Web site problem downloading  source issue

### ISSUE THREAD

**Issue by bdubbs** [openssl/openssl#8982]
We are having a problem downloading openssl-1.1.1b.tar.gz via wget.  If we use 

wget https://openssl.org/source/openssl-1.1.1b.tar.gz

We get the ascii version of the  https://openssl.org/source/ page.  The url above used to work and downloading via a web browser interactively does work, but there does not seem to be a way we can automate the downloads via a list of urls.

Can you help?

  -- Bruce Dubbs
      linuxfromscratch.org

**Comment by kroeckx** [comment]
Use https://openssl.org/source/openssl-1.1.1b.tar.gz, with www.

It seems the redirect is always to http://www.openssl.org, and
drops the rest of the URL.

**Comment by kroeckx** [comment]
So I get:
$ wget -v https://openssl.org/source/openssl-1.1.1b.tar.gz
--2019-05-22 23:45:28--  https://openssl.org/source/openssl-1.1.1b.tar.gz
Resolving openssl.org (openssl.org)... 2001:608:c00:180::1:e5, 194.97.150.230
Connecting to openssl.org (openssl.org)|2001:608:c00:180::1:e5|:443... failed: Connection refused.
Connecting to openssl.org (openssl.org)|194.97.150.230|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.openssl.org [following]
URL transformed to HTTPS due to an HSTS policy
--2019-05-22 23:45:29--  https://www.openssl.org/

So I guess there are 3 configuration issues:
- It's not listening to IPv6
- It's redirecting from https to http
- It's dropping the rest of the URL

@levitte: Can you look at this? At least the redirect to http is something I want fixed.

**Comment by bdubbs** [comment]
Indeed https://www.openssl.org/source/openssl-1.1.1b.tar.gz works.

Thanks.

**Comment by levitte** [comment]
Fixed.

A redirection tune-up wasn't quite right.  It's now been corrected.

**Comment by kroeckx** [comment]
The redirections seem fine now, it's still not listening to IPv6.

**Comment by levitte** [comment]
> it's still not listening to IPv6.

Sorry, didn't catch on to that issue.  It turned out that the AAAA record was incorrect.  The corrected address should reach most caches in about an hour.
